//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractInputEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractInputEntityType">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractBaseInputEntityType">
 *       &lt;attribute name="ExternalReferenceId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExternalSourceId" type="{http://www.w3.org/2001/XMLSchema}string" default="FENERGO" />
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractInputEntityType")
@XmlSeeAlso({
    LegalEntity.class,
    Account.class,
    User.class,
    Address.class,
    MiFID.class,
    Product.class,
    Document.class,
    Case.class,
    APAC.class,
    Association.class,
    DoddFrank.class,
    TradingAgreement.class,
    ContactAddress.class,
    CanadianFIU.class,
    SSI.class,
    LERole.class,
    Contact.class,
    RoleGroup.class,
    EMIR.class,
    MexicanDrivatives.class,
    Relationship.class,
    FATCATAX.class
})
public abstract class AbstractInputEntityType
    extends AbstractBaseInputEntityType
{

    @XmlAttribute(name = "ExternalReferenceId", required = true)
    protected String externalReferenceId;
    @XmlAttribute(name = "ExternalSourceId")
    protected String externalSourceId;

    /**
     * Gets the value of the externalReferenceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalReferenceId() {
        return externalReferenceId;
    }

    /**
     * Sets the value of the externalReferenceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalReferenceId(String value) {
        this.externalReferenceId = value;
    }

    /**
     * Gets the value of the externalSourceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalSourceId() {
        if (externalSourceId == null) {
            return "FENERGO";
        } else {
            return externalSourceId;
        }
    }

    /**
     * Sets the value of the externalSourceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalSourceId(String value) {
        this.externalSourceId = value;
    }

}
