//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Account complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Account">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}AccountAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Account")
public class Account
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "Type", required = true)
    protected String type;
    @XmlAttribute(name = "IMAccountStatus", required = true)
    protected String imAccountStatus;
    @XmlAttribute(name = "AccountIMCode", required = true)
    protected String accountIMCode;
    @XmlAttribute(name = "PortfolioNumber", required = true)
    protected String portfolioNumber;
    @XmlAttribute(name = "AccountID")
    protected String accountID;
    @XmlAttribute(name = "AccountType")
    protected String accountType;
    @XmlAttribute(name = "AccountStatus")
    protected String accountStatus;
    @XmlAttribute(name = "AccountName")
    protected String accountName;
    @XmlAttribute(name = "IMAccountNumber")
    protected String imAccountNumber;
    @XmlAttribute(name = "IMAccountName")
    protected String imAccountName;
    @XmlAttribute(name = "CreditCustomerType")
    protected String creditCustomerType;
    @XmlAttribute(name = "ParentAccountNumber")
    protected String parentAccountNumber;
    @XmlAttribute(name = "ParentAccountName")
    protected String parentAccountName;
    @XmlAttribute(name = "TradingAccountStatus")
    protected String tradingAccountStatus;
    @XmlAttribute(name = "DateAdded")
    protected String dateAdded;
    @XmlAttribute(name = "DateDeleted")
    protected String dateDeleted;
    @XmlAttribute(name = "OMSEntryGroup")
    protected String omsEntryGroup;
    @XmlAttribute(name = "AlertStatus")
    protected String alertStatus;
    @XmlAttribute(name = "TradingValidationDetermination")
    protected String tradingValidationDetermination;
    @XmlAttribute(name = "Comments")
    protected String comments;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the imAccountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMAccountStatus() {
        return imAccountStatus;
    }

    /**
     * Sets the value of the imAccountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMAccountStatus(String value) {
        this.imAccountStatus = value;
    }

    /**
     * Gets the value of the accountIMCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountIMCode() {
        return accountIMCode;
    }

    /**
     * Sets the value of the accountIMCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountIMCode(String value) {
        this.accountIMCode = value;
    }

    /**
     * Gets the value of the portfolioNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioNumber() {
        return portfolioNumber;
    }

    /**
     * Sets the value of the portfolioNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioNumber(String value) {
        this.portfolioNumber = value;
    }

    /**
     * Gets the value of the accountID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountID() {
        return accountID;
    }

    /**
     * Sets the value of the accountID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountID(String value) {
        this.accountID = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountStatus() {
        return accountStatus;
    }

    /**
     * Sets the value of the accountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountStatus(String value) {
        this.accountStatus = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

    /**
     * Gets the value of the imAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMAccountNumber() {
        return imAccountNumber;
    }

    /**
     * Sets the value of the imAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMAccountNumber(String value) {
        this.imAccountNumber = value;
    }

    /**
     * Gets the value of the imAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMAccountName() {
        return imAccountName;
    }

    /**
     * Sets the value of the imAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMAccountName(String value) {
        this.imAccountName = value;
    }

    /**
     * Gets the value of the creditCustomerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCustomerType() {
        return creditCustomerType;
    }

    /**
     * Sets the value of the creditCustomerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCustomerType(String value) {
        this.creditCustomerType = value;
    }

    /**
     * Gets the value of the parentAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentAccountNumber() {
        return parentAccountNumber;
    }

    /**
     * Sets the value of the parentAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentAccountNumber(String value) {
        this.parentAccountNumber = value;
    }

    /**
     * Gets the value of the parentAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentAccountName() {
        return parentAccountName;
    }

    /**
     * Sets the value of the parentAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentAccountName(String value) {
        this.parentAccountName = value;
    }

    /**
     * Gets the value of the tradingAccountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingAccountStatus() {
        return tradingAccountStatus;
    }

    /**
     * Sets the value of the tradingAccountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingAccountStatus(String value) {
        this.tradingAccountStatus = value;
    }

    /**
     * Gets the value of the dateAdded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateAdded() {
        return dateAdded;
    }

    /**
     * Sets the value of the dateAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateAdded(String value) {
        this.dateAdded = value;
    }

    /**
     * Gets the value of the dateDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateDeleted() {
        return dateDeleted;
    }

    /**
     * Sets the value of the dateDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateDeleted(String value) {
        this.dateDeleted = value;
    }

    /**
     * Gets the value of the omsEntryGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOMSEntryGroup() {
        return omsEntryGroup;
    }

    /**
     * Sets the value of the omsEntryGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOMSEntryGroup(String value) {
        this.omsEntryGroup = value;
    }

    /**
     * Gets the value of the alertStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertStatus() {
        return alertStatus;
    }

    /**
     * Sets the value of the alertStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertStatus(String value) {
        this.alertStatus = value;
    }

    /**
     * Gets the value of the tradingValidationDetermination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingValidationDetermination() {
        return tradingValidationDetermination;
    }

    /**
     * Sets the value of the tradingValidationDetermination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingValidationDetermination(String value) {
        this.tradingValidationDetermination = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
