//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APAC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="APAC">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}APACAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APAC")
public class APAC
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "ExemptPersonsFromClearingType", required = true)
    protected String exemptPersonsFromClearingType;
    @XmlAttribute(name = "ExemptionComments", required = true)
    protected String exemptionComments;
    @XmlAttribute(name = "DeferredReportingJurisdiction", required = true)
    protected String deferredReportingJurisdiction;
    @XmlAttribute(name = "RegulatedBy")
    protected String regulatedBy;
    @XmlAttribute(name = "CountryOfIncorporation")
    protected String countryOfIncorporation;
    @XmlAttribute(name = "SWIFTBIC")
    protected String swiftbic;
    @XmlAttribute(name = "IndustrySectorCode")
    protected String industrySectorCode;
    @XmlAttribute(name = "IndustrySectorDesc")
    protected String industrySectorDesc;
    @XmlAttribute(name = "AVOXID")
    protected String avoxid;
    @XmlAttribute(name = "ClassificationRequired")
    protected String classificationRequired;
    @XmlAttribute(name = "MASEntityClassification")
    protected String masEntityClassification;
    @XmlAttribute(name = "BuySideDelegatedReportingToBank")
    protected String buySideDelegatedReportingToBank;
    @XmlAttribute(name = "DeferredReportingCPMasking")
    protected String deferredReportingCPMasking;

    /**
     * Gets the value of the exemptPersonsFromClearingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptPersonsFromClearingType() {
        return exemptPersonsFromClearingType;
    }

    /**
     * Sets the value of the exemptPersonsFromClearingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptPersonsFromClearingType(String value) {
        this.exemptPersonsFromClearingType = value;
    }

    /**
     * Gets the value of the exemptionComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptionComments() {
        return exemptionComments;
    }

    /**
     * Sets the value of the exemptionComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptionComments(String value) {
        this.exemptionComments = value;
    }

    /**
     * Gets the value of the deferredReportingJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferredReportingJurisdiction() {
        return deferredReportingJurisdiction;
    }

    /**
     * Sets the value of the deferredReportingJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferredReportingJurisdiction(String value) {
        this.deferredReportingJurisdiction = value;
    }

    /**
     * Gets the value of the regulatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatedBy() {
        return regulatedBy;
    }

    /**
     * Sets the value of the regulatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatedBy(String value) {
        this.regulatedBy = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the swiftbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSWIFTBIC() {
        return swiftbic;
    }

    /**
     * Sets the value of the swiftbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSWIFTBIC(String value) {
        this.swiftbic = value;
    }

    /**
     * Gets the value of the industrySectorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustrySectorCode() {
        return industrySectorCode;
    }

    /**
     * Sets the value of the industrySectorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustrySectorCode(String value) {
        this.industrySectorCode = value;
    }

    /**
     * Gets the value of the industrySectorDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustrySectorDesc() {
        return industrySectorDesc;
    }

    /**
     * Sets the value of the industrySectorDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustrySectorDesc(String value) {
        this.industrySectorDesc = value;
    }

    /**
     * Gets the value of the avoxid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVOXID() {
        return avoxid;
    }

    /**
     * Sets the value of the avoxid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVOXID(String value) {
        this.avoxid = value;
    }

    /**
     * Gets the value of the classificationRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationRequired() {
        return classificationRequired;
    }

    /**
     * Sets the value of the classificationRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationRequired(String value) {
        this.classificationRequired = value;
    }

    /**
     * Gets the value of the masEntityClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMASEntityClassification() {
        return masEntityClassification;
    }

    /**
     * Sets the value of the masEntityClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMASEntityClassification(String value) {
        this.masEntityClassification = value;
    }

    /**
     * Gets the value of the buySideDelegatedReportingToBank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuySideDelegatedReportingToBank() {
        return buySideDelegatedReportingToBank;
    }

    /**
     * Sets the value of the buySideDelegatedReportingToBank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuySideDelegatedReportingToBank(String value) {
        this.buySideDelegatedReportingToBank = value;
    }

    /**
     * Gets the value of the deferredReportingCPMasking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeferredReportingCPMasking() {
        return deferredReportingCPMasking;
    }

    /**
     * Sets the value of the deferredReportingCPMasking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeferredReportingCPMasking(String value) {
        this.deferredReportingCPMasking = value;
    }

}
