//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Association complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Association">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}AssociationAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Association")
public class Association
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "Relationship", required = true)
    protected String relationship;
    @XmlAttribute(name = "AssociatedEntity", required = true)
    protected String associatedEntity;
    @XmlAttribute(name = "RoleStatus", required = true)
    protected String roleStatus;
    @XmlAttribute(name = "AssociationStatus", required = true)
    protected String associationStatus;
    @XmlAttribute(name = "AssociationName", required = true)
    protected String associationName;
    @XmlAttribute(name = "EntityName", required = true)
    protected String entityName;
    @XmlAttribute(name = "RegisteredState")
    protected String registeredState;
    @XmlAttribute(name = "RegisteredCountry")
    protected String registeredCountry;
    @XmlAttribute(name = "PercentageOwnership")
    protected String percentageOwnership;
    @XmlAttribute(name = "Classification")
    protected String classification;
    @XmlAttribute(name = "ClassificationRelationship")
    protected String classificationRelationship;
    @XmlAttribute(name = "Product")
    protected String product;
    @XmlAttribute(name = "ProductRelationship")
    protected String productRelationship;
    @XmlAttribute(name = "Account")
    protected String account;
    @XmlAttribute(name = "AccountRelationship")
    protected String accountRelationship;
    @XmlAttribute(name = "AssociationID")
    protected String associationID;
    @XmlAttribute(name = "LinkTo")
    protected String linkTo;
    @XmlAttribute(name = "LegalEntityID")
    protected String legalEntityID;
    @XmlAttribute(name = "ActiveFrom")
    protected String activeFrom;
    @XmlAttribute(name = "ActiveTo")
    protected String activeTo;
    @XmlAttribute(name = "LastUpdatedDate")
    protected String lastUpdatedDate;
    @XmlAttribute(name = "LastUpdatedByt")
    protected String lastUpdatedByt;
    @XmlAttribute(name = "PositionRole")
    protected String positionRole;
    @XmlAttribute(name = "EntityType")
    protected String entityType;
    @XmlAttribute(name = "CountryOfIncorporation")
    protected String countryOfIncorporation;
    @XmlAttribute(name = "IsPubliclyListed")
    protected String isPubliclyListed;
    @XmlAttribute(name = "IsRegulated")
    protected String isRegulated;
    @XmlAttribute(name = "NameOfListedExchange")
    protected String nameOfListedExchange;
    @XmlAttribute(name = "ExchangeTicker")
    protected String exchangeTicker;
    @XmlAttribute(name = "IsApprovedExchange")
    protected String isApprovedExchange;
    @XmlAttribute(name = "RegulatoryAuthority")
    protected String regulatoryAuthority;
    @XmlAttribute(name = "RegulatorCountry")
    protected String regulatorCountry;
    @XmlAttribute(name = "ApprovedRegulator")
    protected String approvedRegulator;
    @XmlAttribute(name = "GovtIDNumber")
    protected String govtIDNumber;
    @XmlAttribute(name = "GovtIDType")
    protected String govtIDType;
    @XmlAttribute(name = "IsGovernmentBody")
    protected String isGovernmentBody;
    @XmlAttribute(name = "PercentageKYCEntityOwnership")
    protected String percentageKYCEntityOwnership;
    @XmlAttribute(name = "BOOwnershipLevel")
    protected String boOwnershipLevel;
    @XmlAttribute(name = "OwnedNonKYCEntityName")
    protected String ownedNonKYCEntityName;
    @XmlAttribute(name = "OwnedNonKYCEntityMEI")
    protected String ownedNonKYCEntityMEI;
    @XmlAttribute(name = "PercentageNonKYCEntityOwned")
    protected String percentageNonKYCEntityOwned;
    @XmlAttribute(name = "LegalForm")
    protected String legalForm;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "AddressType")
    protected String addressType;
    @XmlAttribute(name = "AddressLine1")
    protected String addressLine1;
    @XmlAttribute(name = "AddressLine2")
    protected String addressLine2;
    @XmlAttribute(name = "TownCity")
    protected String townCity;
    @XmlAttribute(name = "StateCounty")
    protected String stateCounty;
    @XmlAttribute(name = "Country")
    protected String country;

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationship(String value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the associatedEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedEntity() {
        return associatedEntity;
    }

    /**
     * Sets the value of the associatedEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedEntity(String value) {
        this.associatedEntity = value;
    }

    /**
     * Gets the value of the roleStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleStatus() {
        return roleStatus;
    }

    /**
     * Sets the value of the roleStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleStatus(String value) {
        this.roleStatus = value;
    }

    /**
     * Gets the value of the associationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociationStatus() {
        return associationStatus;
    }

    /**
     * Sets the value of the associationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociationStatus(String value) {
        this.associationStatus = value;
    }

    /**
     * Gets the value of the associationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociationName() {
        return associationName;
    }

    /**
     * Sets the value of the associationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociationName(String value) {
        this.associationName = value;
    }

    /**
     * Gets the value of the entityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * Sets the value of the entityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityName(String value) {
        this.entityName = value;
    }

    /**
     * Gets the value of the registeredState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisteredState() {
        return registeredState;
    }

    /**
     * Sets the value of the registeredState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisteredState(String value) {
        this.registeredState = value;
    }

    /**
     * Gets the value of the registeredCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegisteredCountry() {
        return registeredCountry;
    }

    /**
     * Sets the value of the registeredCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegisteredCountry(String value) {
        this.registeredCountry = value;
    }

    /**
     * Gets the value of the percentageOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentageOwnership() {
        return percentageOwnership;
    }

    /**
     * Sets the value of the percentageOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentageOwnership(String value) {
        this.percentageOwnership = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassification(String value) {
        this.classification = value;
    }

    /**
     * Gets the value of the classificationRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationRelationship() {
        return classificationRelationship;
    }

    /**
     * Sets the value of the classificationRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationRelationship(String value) {
        this.classificationRelationship = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the productRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductRelationship() {
        return productRelationship;
    }

    /**
     * Sets the value of the productRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductRelationship(String value) {
        this.productRelationship = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccount(String value) {
        this.account = value;
    }

    /**
     * Gets the value of the accountRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountRelationship() {
        return accountRelationship;
    }

    /**
     * Sets the value of the accountRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountRelationship(String value) {
        this.accountRelationship = value;
    }

    /**
     * Gets the value of the associationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociationID() {
        return associationID;
    }

    /**
     * Sets the value of the associationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociationID(String value) {
        this.associationID = value;
    }

    /**
     * Gets the value of the linkTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkTo() {
        return linkTo;
    }

    /**
     * Sets the value of the linkTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkTo(String value) {
        this.linkTo = value;
    }

    /**
     * Gets the value of the legalEntityID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityID() {
        return legalEntityID;
    }

    /**
     * Sets the value of the legalEntityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityID(String value) {
        this.legalEntityID = value;
    }

    /**
     * Gets the value of the activeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFrom() {
        return activeFrom;
    }

    /**
     * Sets the value of the activeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFrom(String value) {
        this.activeFrom = value;
    }

    /**
     * Gets the value of the activeTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveTo() {
        return activeTo;
    }

    /**
     * Sets the value of the activeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveTo(String value) {
        this.activeTo = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedDate(String value) {
        this.lastUpdatedDate = value;
    }

    /**
     * Gets the value of the lastUpdatedByt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedByt() {
        return lastUpdatedByt;
    }

    /**
     * Sets the value of the lastUpdatedByt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedByt(String value) {
        this.lastUpdatedByt = value;
    }

    /**
     * Gets the value of the positionRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionRole() {
        return positionRole;
    }

    /**
     * Sets the value of the positionRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionRole(String value) {
        this.positionRole = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the isPubliclyListed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPubliclyListed() {
        return isPubliclyListed;
    }

    /**
     * Sets the value of the isPubliclyListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPubliclyListed(String value) {
        this.isPubliclyListed = value;
    }

    /**
     * Gets the value of the isRegulated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsRegulated() {
        return isRegulated;
    }

    /**
     * Sets the value of the isRegulated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsRegulated(String value) {
        this.isRegulated = value;
    }

    /**
     * Gets the value of the nameOfListedExchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfListedExchange() {
        return nameOfListedExchange;
    }

    /**
     * Sets the value of the nameOfListedExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfListedExchange(String value) {
        this.nameOfListedExchange = value;
    }

    /**
     * Gets the value of the exchangeTicker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeTicker() {
        return exchangeTicker;
    }

    /**
     * Sets the value of the exchangeTicker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeTicker(String value) {
        this.exchangeTicker = value;
    }

    /**
     * Gets the value of the isApprovedExchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsApprovedExchange() {
        return isApprovedExchange;
    }

    /**
     * Sets the value of the isApprovedExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsApprovedExchange(String value) {
        this.isApprovedExchange = value;
    }

    /**
     * Gets the value of the regulatoryAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatoryAuthority() {
        return regulatoryAuthority;
    }

    /**
     * Sets the value of the regulatoryAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatoryAuthority(String value) {
        this.regulatoryAuthority = value;
    }

    /**
     * Gets the value of the regulatorCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatorCountry() {
        return regulatorCountry;
    }

    /**
     * Sets the value of the regulatorCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatorCountry(String value) {
        this.regulatorCountry = value;
    }

    /**
     * Gets the value of the approvedRegulator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedRegulator() {
        return approvedRegulator;
    }

    /**
     * Sets the value of the approvedRegulator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedRegulator(String value) {
        this.approvedRegulator = value;
    }

    /**
     * Gets the value of the govtIDNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovtIDNumber() {
        return govtIDNumber;
    }

    /**
     * Sets the value of the govtIDNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovtIDNumber(String value) {
        this.govtIDNumber = value;
    }

    /**
     * Gets the value of the govtIDType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGovtIDType() {
        return govtIDType;
    }

    /**
     * Sets the value of the govtIDType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGovtIDType(String value) {
        this.govtIDType = value;
    }

    /**
     * Gets the value of the isGovernmentBody property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsGovernmentBody() {
        return isGovernmentBody;
    }

    /**
     * Sets the value of the isGovernmentBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsGovernmentBody(String value) {
        this.isGovernmentBody = value;
    }

    /**
     * Gets the value of the percentageKYCEntityOwnership property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentageKYCEntityOwnership() {
        return percentageKYCEntityOwnership;
    }

    /**
     * Sets the value of the percentageKYCEntityOwnership property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentageKYCEntityOwnership(String value) {
        this.percentageKYCEntityOwnership = value;
    }

    /**
     * Gets the value of the boOwnershipLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBOOwnershipLevel() {
        return boOwnershipLevel;
    }

    /**
     * Sets the value of the boOwnershipLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBOOwnershipLevel(String value) {
        this.boOwnershipLevel = value;
    }

    /**
     * Gets the value of the ownedNonKYCEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnedNonKYCEntityName() {
        return ownedNonKYCEntityName;
    }

    /**
     * Sets the value of the ownedNonKYCEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnedNonKYCEntityName(String value) {
        this.ownedNonKYCEntityName = value;
    }

    /**
     * Gets the value of the ownedNonKYCEntityMEI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnedNonKYCEntityMEI() {
        return ownedNonKYCEntityMEI;
    }

    /**
     * Sets the value of the ownedNonKYCEntityMEI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnedNonKYCEntityMEI(String value) {
        this.ownedNonKYCEntityMEI = value;
    }

    /**
     * Gets the value of the percentageNonKYCEntityOwned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentageNonKYCEntityOwned() {
        return percentageNonKYCEntityOwned;
    }

    /**
     * Sets the value of the percentageNonKYCEntityOwned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentageNonKYCEntityOwned(String value) {
        this.percentageNonKYCEntityOwned = value;
    }

    /**
     * Gets the value of the legalForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalForm() {
        return legalForm;
    }

    /**
     * Sets the value of the legalForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalForm(String value) {
        this.legalForm = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the addressType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * Sets the value of the addressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressType(String value) {
        this.addressType = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the townCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTownCity() {
        return townCity;
    }

    /**
     * Sets the value of the townCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTownCity(String value) {
        this.townCity = value;
    }

    /**
     * Gets the value of the stateCounty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCounty() {
        return stateCounty;
    }

    /**
     * Sets the value of the stateCounty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCounty(String value) {
        this.stateCounty = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

}
