//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountryEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CountryEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Ireland"/>
 *     &lt;enumeration value="Portugal"/>
 *     &lt;enumeration value="UK"/>
 *     &lt;enumeration value="USA"/>
 *     &lt;enumeration value="Spain"/>
 *     &lt;enumeration value="Hungary"/>
 *     &lt;enumeration value="Czech Republic"/>
 *     &lt;enumeration value="France"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CountryEnum")
@XmlEnum
public enum CountryEnum {

    @XmlEnumValue("Ireland")
    IRELAND("Ireland"),
    @XmlEnumValue("Portugal")
    PORTUGAL("Portugal"),
    UK("UK"),
    USA("USA"),
    @XmlEnumValue("Spain")
    SPAIN("Spain"),
    @XmlEnumValue("Hungary")
    HUNGARY("Hungary"),
    @XmlEnumValue("Czech Republic")
    CZECH_REPUBLIC("Czech Republic"),
    @XmlEnumValue("France")
    FRANCE("France");
    private final String value;

    CountryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CountryEnum fromValue(String v) {
        for (CountryEnum c: CountryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
