//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}DocumentAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document")
public class Document
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "DocumentSource", required = true)
    protected String documentSource;
    @XmlAttribute(name = "DocumentDirection", required = true)
    protected String documentDirection;
    @XmlAttribute(name = "DocumentCategory", required = true)
    protected String documentCategory;
    @XmlAttribute(name = "DocumentType", required = true)
    protected String documentType;
    @XmlAttribute(name = "DocumentName", required = true)
    protected String documentName;
    @XmlAttribute(name = "DocumentTemplate", required = true)
    protected String documentTemplate;
    @XmlAttribute(name = "OutputType", required = true)
    protected String outputType;
    @XmlAttribute(name = "PackTemplate", required = true)
    protected String packTemplate;
    @XmlAttribute(name = "MergedDocumentTemplate", required = true)
    protected String mergedDocumentTemplate;
    @XmlAttribute(name = "FilelessDocument")
    protected String filelessDocument;
    @XmlAttribute(name = "Filelocation")
    protected String filelocation;
    @XmlAttribute(name = "Current")
    protected String current;
    @XmlAttribute(name = "SignedAndInFull")
    protected String signedAndInFull;
    @XmlAttribute(name = "Legible")
    protected String legible;
    @XmlAttribute(name = "AnnotatedIfInLanguageOtherThanEnglish")
    protected String annotatedIfInLanguageOtherThanEnglish;
    @XmlAttribute(name = "EffectiveDate")
    protected String effectiveDate;
    @XmlAttribute(name = "ExpirationDate")
    protected String expirationDate;
    @XmlAttribute(name = "DocumentIdentificationNumber")
    protected String documentIdentificationNumber;
    @XmlAttribute(name = "IssuerOfTheDocument")
    protected String issuerOfTheDocument;
    @XmlAttribute(name = "DateOfIssuance")
    protected String dateOfIssuance;
    @XmlAttribute(name = "PlaceOfIssuance")
    protected String placeOfIssuance;

    /**
     * Gets the value of the documentSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentSource() {
        return documentSource;
    }

    /**
     * Sets the value of the documentSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentSource(String value) {
        this.documentSource = value;
    }

    /**
     * Gets the value of the documentDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentDirection() {
        return documentDirection;
    }

    /**
     * Sets the value of the documentDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentDirection(String value) {
        this.documentDirection = value;
    }

    /**
     * Gets the value of the documentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentCategory() {
        return documentCategory;
    }

    /**
     * Sets the value of the documentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentCategory(String value) {
        this.documentCategory = value;
    }

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the documentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * Sets the value of the documentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentName(String value) {
        this.documentName = value;
    }

    /**
     * Gets the value of the documentTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentTemplate() {
        return documentTemplate;
    }

    /**
     * Sets the value of the documentTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentTemplate(String value) {
        this.documentTemplate = value;
    }

    /**
     * Gets the value of the outputType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputType(String value) {
        this.outputType = value;
    }

    /**
     * Gets the value of the packTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackTemplate() {
        return packTemplate;
    }

    /**
     * Sets the value of the packTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackTemplate(String value) {
        this.packTemplate = value;
    }

    /**
     * Gets the value of the mergedDocumentTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMergedDocumentTemplate() {
        return mergedDocumentTemplate;
    }

    /**
     * Sets the value of the mergedDocumentTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMergedDocumentTemplate(String value) {
        this.mergedDocumentTemplate = value;
    }

    /**
     * Gets the value of the filelessDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilelessDocument() {
        return filelessDocument;
    }

    /**
     * Sets the value of the filelessDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilelessDocument(String value) {
        this.filelessDocument = value;
    }

    /**
     * Gets the value of the filelocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilelocation() {
        return filelocation;
    }

    /**
     * Sets the value of the filelocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilelocation(String value) {
        this.filelocation = value;
    }

    /**
     * Gets the value of the current property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrent() {
        return current;
    }

    /**
     * Sets the value of the current property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrent(String value) {
        this.current = value;
    }

    /**
     * Gets the value of the signedAndInFull property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedAndInFull() {
        return signedAndInFull;
    }

    /**
     * Sets the value of the signedAndInFull property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedAndInFull(String value) {
        this.signedAndInFull = value;
    }

    /**
     * Gets the value of the legible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegible() {
        return legible;
    }

    /**
     * Sets the value of the legible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegible(String value) {
        this.legible = value;
    }

    /**
     * Gets the value of the annotatedIfInLanguageOtherThanEnglish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotatedIfInLanguageOtherThanEnglish() {
        return annotatedIfInLanguageOtherThanEnglish;
    }

    /**
     * Sets the value of the annotatedIfInLanguageOtherThanEnglish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotatedIfInLanguageOtherThanEnglish(String value) {
        this.annotatedIfInLanguageOtherThanEnglish = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDate(String value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the documentIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentIdentificationNumber() {
        return documentIdentificationNumber;
    }

    /**
     * Sets the value of the documentIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentIdentificationNumber(String value) {
        this.documentIdentificationNumber = value;
    }

    /**
     * Gets the value of the issuerOfTheDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerOfTheDocument() {
        return issuerOfTheDocument;
    }

    /**
     * Sets the value of the issuerOfTheDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerOfTheDocument(String value) {
        this.issuerOfTheDocument = value;
    }

    /**
     * Gets the value of the dateOfIssuance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfIssuance() {
        return dateOfIssuance;
    }

    /**
     * Sets the value of the dateOfIssuance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfIssuance(String value) {
        this.dateOfIssuance = value;
    }

    /**
     * Gets the value of the placeOfIssuance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfIssuance() {
        return placeOfIssuance;
    }

    /**
     * Sets the value of the placeOfIssuance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfIssuance(String value) {
        this.placeOfIssuance = value;
    }

}
