//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DoddFrank complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DoddFrank">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}DoddFrankAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DoddFrank")
public class DoddFrank
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "Status", required = true)
    protected String status;
    @XmlAttribute(name = "EBCComplianceComments", required = true)
    protected String ebcComplianceComments;
    @XmlAttribute(name = "SwapDocAmendmentsComments", required = true)
    protected String swapDocAmendmentsComments;
    @XmlAttribute(name = "EBCComplianceStatus")
    protected String ebcComplianceStatus;
    @XmlAttribute(name = "SwapDocAmendmentsComplianceStatus")
    protected String swapDocAmendmentsComplianceStatus;
    @XmlAttribute(name = "LegalEntityName")
    protected String legalEntityName;
    @XmlAttribute(name = "LegalEntityType")
    protected String legalEntityType;
    @XmlAttribute(name = "LEI")
    protected String lei;
    @XmlAttribute(name = "CountryOfIncorporation")
    protected String countryOfIncorporation;
    @XmlAttribute(name = "MarkitLegalName")
    protected String markitLegalName;
    @XmlAttribute(name = "MarkitInstitutionName")
    protected String markitInstitutionName;
    @XmlAttribute(name = "NAICCode")
    protected String naicCode;
    @XmlAttribute(name = "SICCode")
    protected String sicCode;
    @XmlAttribute(name = "PrimaryBusinessLocation")
    protected String primaryBusinessLocation;
    @XmlAttribute(name = "BusinessMarkets")
    protected String businessMarkets;
    @XmlAttribute(name = "RegulatedBy")
    protected String regulatedBy;
    @XmlAttribute(name = "DesignatedBusinessLine")
    protected String designatedBusinessLine;
    @XmlAttribute(name = "ClientContact")
    protected String clientContact;
    @XmlAttribute(name = "ProtocolInfoSource")
    protected String protocolInfoSource;
    @XmlAttribute(name = "PrincipalBusiness")
    protected String principalBusiness;
    @XmlAttribute(name = "TradingAgreementType")
    protected String tradingAgreementType;
    @XmlAttribute(name = "Protocol1AdherenceLetter")
    protected String protocol1AdherenceLetter;
    @XmlAttribute(name = "PCAPrincipalType")
    protected String pcaPrincipalType;
    @XmlAttribute(name = "ECPTypes")
    protected String ecpTypes;
    @XmlAttribute(name = "OtherEligiblePersonComments")
    protected String otherEligiblePersonComments;
    @XmlAttribute(name = "CommodityPool")
    protected String commodityPool;
    @XmlAttribute(name = "ActiveFund")
    protected String activeFund;
    @XmlAttribute(name = "Protocol1_0Schedules")
    protected String protocol10Schedules;
    @XmlAttribute(name = "SpecialEntityType")
    protected String specialEntityType;
    @XmlAttribute(name = "OralDisclosureOfPreTrademarks")
    protected String oralDisclosureOfPreTrademarks;
    @XmlAttribute(name = "FinancialEntity1_0")
    protected String financialEntity10;
    @XmlAttribute(name = "DFTermsAgreementElections")
    protected String dfTermsAgreementElections;
    @XmlAttribute(name = "DFNotificationsEmail")
    protected String dfNotificationsEmail;
    @XmlAttribute(name = "SpecificInstructions")
    protected String specificInstructions;
    @XmlAttribute(name = "Category2Entity")
    protected String category2Entity;
    @XmlAttribute(name = "CoveredFXTransaction")
    protected String coveredFXTransaction;
    @XmlAttribute(name = "CoveredDerivativesTransaction")
    protected String coveredDerivativesTransaction;
    @XmlAttribute(name = "PreTradeMarkTransaction")
    protected String preTradeMarkTransaction;
    @XmlAttribute(name = "SpecifiedFXCommodityPool")
    protected String specifiedFXCommodityPool;
    @XmlAttribute(name = "NonUSFXCommodityPool")
    protected String nonUSFXCommodityPool;
    @XmlAttribute(name = "AllECPFXCommodityPool")
    protected String allECPFXCommodityPool;
    @XmlAttribute(name = "PCASignatoryTitle")
    protected String pcaSignatoryTitle;
    @XmlAttribute(name = "PCASignatory")
    protected String pcaSignatory;
    @XmlAttribute(name = "DFTermsAgreementDateCompleted")
    protected String dfTermsAgreementDateCompleted;
    @XmlAttribute(name = "MarkitFileNotes")
    protected String markitFileNotes;
    @XmlAttribute(name = "ECPSpecialEntityElectionAgreement")
    protected String ecpSpecialEntityElectionAgreement;
    @XmlAttribute(name = "ECPSpecialEntityElectionAgreementDate")
    protected String ecpSpecialEntityElectionAgreementDate;
    @XmlAttribute(name = "NonSpecialEntityTradingLetterAgreement")
    protected String nonSpecialEntityTradingLetterAgreement;
    @XmlAttribute(name = "NonSpecialEntityTradingLetterAgreementDate")
    protected String nonSpecialEntityTradingLetterAgreementDate;
    @XmlAttribute(name = "InstitutionSuitabilityAgreement")
    protected String institutionSuitabilityAgreement;
    @XmlAttribute(name = "InstitutionSuitabilityAgreementDate")
    protected String institutionSuitabilityAgreementDate;
    @XmlAttribute(name = "SpecialEntityTradingLetterAgreement")
    protected String specialEntityTradingLetterAgreement;
    @XmlAttribute(name = "SpecialEntityTradingLetterAgreementDate")
    protected String specialEntityTradingLetterAgreementDate;
    @XmlAttribute(name = "NegativeConsentLetterRequired")
    protected String negativeConsentLetterRequired;
    @XmlAttribute(name = "NegativeConsentLetterSentDate")
    protected String negativeConsentLetterSentDate;
    @XmlAttribute(name = "DisclosuresProvided")
    protected String disclosuresProvided;
    @XmlAttribute(name = "DisclosuresProvidedDate")
    protected String disclosuresProvidedDate;
    @XmlAttribute(name = "DeliveryMechanismOfDisclosures")
    protected String deliveryMechanismOfDisclosures;
    @XmlAttribute(name = "Protocol2AdherenceLetter")
    protected String protocol2AdherenceLetter;
    @XmlAttribute(name = "AdherenceLetterID")
    protected String adherenceLetterID;
    @XmlAttribute(name = "SECIssuerFiler")
    protected String secIssuerFiler;
    @XmlAttribute(name = "ElectionApproval")
    protected String electionApproval;
    @XmlAttribute(name = "CFTCSwapEntity")
    protected String cftcSwapEntity;
    @XmlAttribute(name = "FinancialEntity2_0")
    protected String financialEntity20;
    @XmlAttribute(name = "FinancialCompany")
    protected String financialCompany;
    @XmlAttribute(name = "InsuredDepositoryInstitution")
    protected String insuredDepositoryInstitution;
    @XmlAttribute(name = "DeliveryOfNoticesEmail")
    protected String deliveryOfNoticesEmail;
    @XmlAttribute(name = "RiskValuationsEmai")
    protected String riskValuationsEmai;
    @XmlAttribute(name = "PortfolioDataEmail")
    protected String portfolioDataEmail;
    @XmlAttribute(name = "LocalBusinessDayCityOrCities")
    protected String localBusinessDayCityOrCities;
    @XmlAttribute(name = "Protocol2_0Schedules")
    protected String protocol20Schedules;
    @XmlAttribute(name = "March2013DFMasterAgreement")
    protected String march2013DFMasterAgreement;
    @XmlAttribute(name = "ReviewExchangePortfolioData")
    protected String reviewExchangePortfolioData;
    @XmlAttribute(name = "AgreeToReconcileSDRData")
    protected String agreeToReconcileSDRData;
    @XmlAttribute(name = "StandingEndUserExemption")
    protected String standingEndUserExemption;
    @XmlAttribute(name = "StandingOptOutOfAnnualFiling")
    protected String standingOptOutOfAnnualFiling;
    @XmlAttribute(name = "FinanceAffiliateExemption")
    protected String financeAffiliateExemption;
    @XmlAttribute(name = "HedgingAffiliateExemption")
    protected String hedgingAffiliateExemption;
    @XmlAttribute(name = "SmallBankExemption")
    protected String smallBankExemption;
    @XmlAttribute(name = "UnclearedSwapFinancialObligations")
    protected String unclearedSwapFinancialObligations;
    @XmlAttribute(name = "USPersonRepresentation")
    protected String usPersonRepresentation;
    @XmlAttribute(name = "AffiliateConduitRepresentations")
    protected String affiliateConduitRepresentations;
    @XmlAttribute(name = "GuaranteeRepresentationsGeneral")
    protected String guaranteeRepresentationsGeneral;
    @XmlAttribute(name = "FinancialEntityGuarantees")
    protected String financialEntityGuarantees;
    @XmlAttribute(name = "SwapDealerAffiliateGuarantees")
    protected String swapDealerAffiliateGuarantees;
    @XmlAttribute(name = "WrittenAgreement")
    protected String writtenAgreement;
    @XmlAttribute(name = "DateOfWrittenAgreement")
    protected String dateOfWrittenAgreement;
    @XmlAttribute(name = "ReconType")
    protected String reconType;
    @XmlAttribute(name = "SubstitutedCompliance")
    protected String substitutedCompliance;
    @XmlAttribute(name = "Comments")
    protected String comments;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the ebcComplianceComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBCComplianceComments() {
        return ebcComplianceComments;
    }

    /**
     * Sets the value of the ebcComplianceComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBCComplianceComments(String value) {
        this.ebcComplianceComments = value;
    }

    /**
     * Gets the value of the swapDocAmendmentsComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwapDocAmendmentsComments() {
        return swapDocAmendmentsComments;
    }

    /**
     * Sets the value of the swapDocAmendmentsComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwapDocAmendmentsComments(String value) {
        this.swapDocAmendmentsComments = value;
    }

    /**
     * Gets the value of the ebcComplianceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBCComplianceStatus() {
        return ebcComplianceStatus;
    }

    /**
     * Sets the value of the ebcComplianceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBCComplianceStatus(String value) {
        this.ebcComplianceStatus = value;
    }

    /**
     * Gets the value of the swapDocAmendmentsComplianceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwapDocAmendmentsComplianceStatus() {
        return swapDocAmendmentsComplianceStatus;
    }

    /**
     * Sets the value of the swapDocAmendmentsComplianceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwapDocAmendmentsComplianceStatus(String value) {
        this.swapDocAmendmentsComplianceStatus = value;
    }

    /**
     * Gets the value of the legalEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityName() {
        return legalEntityName;
    }

    /**
     * Sets the value of the legalEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityName(String value) {
        this.legalEntityName = value;
    }

    /**
     * Gets the value of the legalEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityType() {
        return legalEntityType;
    }

    /**
     * Sets the value of the legalEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityType(String value) {
        this.legalEntityType = value;
    }

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the markitLegalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkitLegalName() {
        return markitLegalName;
    }

    /**
     * Sets the value of the markitLegalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkitLegalName(String value) {
        this.markitLegalName = value;
    }

    /**
     * Gets the value of the markitInstitutionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkitInstitutionName() {
        return markitInstitutionName;
    }

    /**
     * Sets the value of the markitInstitutionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkitInstitutionName(String value) {
        this.markitInstitutionName = value;
    }

    /**
     * Gets the value of the naicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICCode() {
        return naicCode;
    }

    /**
     * Sets the value of the naicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICCode(String value) {
        this.naicCode = value;
    }

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSICCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSICCode(String value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the primaryBusinessLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryBusinessLocation() {
        return primaryBusinessLocation;
    }

    /**
     * Sets the value of the primaryBusinessLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryBusinessLocation(String value) {
        this.primaryBusinessLocation = value;
    }

    /**
     * Gets the value of the businessMarkets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessMarkets() {
        return businessMarkets;
    }

    /**
     * Sets the value of the businessMarkets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessMarkets(String value) {
        this.businessMarkets = value;
    }

    /**
     * Gets the value of the regulatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatedBy() {
        return regulatedBy;
    }

    /**
     * Sets the value of the regulatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatedBy(String value) {
        this.regulatedBy = value;
    }

    /**
     * Gets the value of the designatedBusinessLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignatedBusinessLine() {
        return designatedBusinessLine;
    }

    /**
     * Sets the value of the designatedBusinessLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignatedBusinessLine(String value) {
        this.designatedBusinessLine = value;
    }

    /**
     * Gets the value of the clientContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientContact() {
        return clientContact;
    }

    /**
     * Sets the value of the clientContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientContact(String value) {
        this.clientContact = value;
    }

    /**
     * Gets the value of the protocolInfoSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolInfoSource() {
        return protocolInfoSource;
    }

    /**
     * Sets the value of the protocolInfoSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolInfoSource(String value) {
        this.protocolInfoSource = value;
    }

    /**
     * Gets the value of the principalBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipalBusiness() {
        return principalBusiness;
    }

    /**
     * Sets the value of the principalBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipalBusiness(String value) {
        this.principalBusiness = value;
    }

    /**
     * Gets the value of the tradingAgreementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingAgreementType() {
        return tradingAgreementType;
    }

    /**
     * Sets the value of the tradingAgreementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingAgreementType(String value) {
        this.tradingAgreementType = value;
    }

    /**
     * Gets the value of the protocol1AdherenceLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol1AdherenceLetter() {
        return protocol1AdherenceLetter;
    }

    /**
     * Sets the value of the protocol1AdherenceLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol1AdherenceLetter(String value) {
        this.protocol1AdherenceLetter = value;
    }

    /**
     * Gets the value of the pcaPrincipalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCAPrincipalType() {
        return pcaPrincipalType;
    }

    /**
     * Sets the value of the pcaPrincipalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCAPrincipalType(String value) {
        this.pcaPrincipalType = value;
    }

    /**
     * Gets the value of the ecpTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPTypes() {
        return ecpTypes;
    }

    /**
     * Sets the value of the ecpTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPTypes(String value) {
        this.ecpTypes = value;
    }

    /**
     * Gets the value of the otherEligiblePersonComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherEligiblePersonComments() {
        return otherEligiblePersonComments;
    }

    /**
     * Sets the value of the otherEligiblePersonComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherEligiblePersonComments(String value) {
        this.otherEligiblePersonComments = value;
    }

    /**
     * Gets the value of the commodityPool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityPool() {
        return commodityPool;
    }

    /**
     * Sets the value of the commodityPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityPool(String value) {
        this.commodityPool = value;
    }

    /**
     * Gets the value of the activeFund property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActiveFund() {
        return activeFund;
    }

    /**
     * Sets the value of the activeFund property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActiveFund(String value) {
        this.activeFund = value;
    }

    /**
     * Gets the value of the protocol10Schedules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol10Schedules() {
        return protocol10Schedules;
    }

    /**
     * Sets the value of the protocol10Schedules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol10Schedules(String value) {
        this.protocol10Schedules = value;
    }

    /**
     * Gets the value of the specialEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialEntityType() {
        return specialEntityType;
    }

    /**
     * Sets the value of the specialEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialEntityType(String value) {
        this.specialEntityType = value;
    }

    /**
     * Gets the value of the oralDisclosureOfPreTrademarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOralDisclosureOfPreTrademarks() {
        return oralDisclosureOfPreTrademarks;
    }

    /**
     * Sets the value of the oralDisclosureOfPreTrademarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOralDisclosureOfPreTrademarks(String value) {
        this.oralDisclosureOfPreTrademarks = value;
    }

    /**
     * Gets the value of the financialEntity10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialEntity10() {
        return financialEntity10;
    }

    /**
     * Sets the value of the financialEntity10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialEntity10(String value) {
        this.financialEntity10 = value;
    }

    /**
     * Gets the value of the dfTermsAgreementElections property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFTermsAgreementElections() {
        return dfTermsAgreementElections;
    }

    /**
     * Sets the value of the dfTermsAgreementElections property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFTermsAgreementElections(String value) {
        this.dfTermsAgreementElections = value;
    }

    /**
     * Gets the value of the dfNotificationsEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFNotificationsEmail() {
        return dfNotificationsEmail;
    }

    /**
     * Sets the value of the dfNotificationsEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFNotificationsEmail(String value) {
        this.dfNotificationsEmail = value;
    }

    /**
     * Gets the value of the specificInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificInstructions() {
        return specificInstructions;
    }

    /**
     * Sets the value of the specificInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificInstructions(String value) {
        this.specificInstructions = value;
    }

    /**
     * Gets the value of the category2Entity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory2Entity() {
        return category2Entity;
    }

    /**
     * Sets the value of the category2Entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory2Entity(String value) {
        this.category2Entity = value;
    }

    /**
     * Gets the value of the coveredFXTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoveredFXTransaction() {
        return coveredFXTransaction;
    }

    /**
     * Sets the value of the coveredFXTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoveredFXTransaction(String value) {
        this.coveredFXTransaction = value;
    }

    /**
     * Gets the value of the coveredDerivativesTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoveredDerivativesTransaction() {
        return coveredDerivativesTransaction;
    }

    /**
     * Sets the value of the coveredDerivativesTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoveredDerivativesTransaction(String value) {
        this.coveredDerivativesTransaction = value;
    }

    /**
     * Gets the value of the preTradeMarkTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreTradeMarkTransaction() {
        return preTradeMarkTransaction;
    }

    /**
     * Sets the value of the preTradeMarkTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreTradeMarkTransaction(String value) {
        this.preTradeMarkTransaction = value;
    }

    /**
     * Gets the value of the specifiedFXCommodityPool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecifiedFXCommodityPool() {
        return specifiedFXCommodityPool;
    }

    /**
     * Sets the value of the specifiedFXCommodityPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecifiedFXCommodityPool(String value) {
        this.specifiedFXCommodityPool = value;
    }

    /**
     * Gets the value of the nonUSFXCommodityPool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonUSFXCommodityPool() {
        return nonUSFXCommodityPool;
    }

    /**
     * Sets the value of the nonUSFXCommodityPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonUSFXCommodityPool(String value) {
        this.nonUSFXCommodityPool = value;
    }

    /**
     * Gets the value of the allECPFXCommodityPool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllECPFXCommodityPool() {
        return allECPFXCommodityPool;
    }

    /**
     * Sets the value of the allECPFXCommodityPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllECPFXCommodityPool(String value) {
        this.allECPFXCommodityPool = value;
    }

    /**
     * Gets the value of the pcaSignatoryTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCASignatoryTitle() {
        return pcaSignatoryTitle;
    }

    /**
     * Sets the value of the pcaSignatoryTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCASignatoryTitle(String value) {
        this.pcaSignatoryTitle = value;
    }

    /**
     * Gets the value of the pcaSignatory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCASignatory() {
        return pcaSignatory;
    }

    /**
     * Sets the value of the pcaSignatory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCASignatory(String value) {
        this.pcaSignatory = value;
    }

    /**
     * Gets the value of the dfTermsAgreementDateCompleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFTermsAgreementDateCompleted() {
        return dfTermsAgreementDateCompleted;
    }

    /**
     * Sets the value of the dfTermsAgreementDateCompleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFTermsAgreementDateCompleted(String value) {
        this.dfTermsAgreementDateCompleted = value;
    }

    /**
     * Gets the value of the markitFileNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkitFileNotes() {
        return markitFileNotes;
    }

    /**
     * Sets the value of the markitFileNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkitFileNotes(String value) {
        this.markitFileNotes = value;
    }

    /**
     * Gets the value of the ecpSpecialEntityElectionAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPSpecialEntityElectionAgreement() {
        return ecpSpecialEntityElectionAgreement;
    }

    /**
     * Sets the value of the ecpSpecialEntityElectionAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPSpecialEntityElectionAgreement(String value) {
        this.ecpSpecialEntityElectionAgreement = value;
    }

    /**
     * Gets the value of the ecpSpecialEntityElectionAgreementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPSpecialEntityElectionAgreementDate() {
        return ecpSpecialEntityElectionAgreementDate;
    }

    /**
     * Sets the value of the ecpSpecialEntityElectionAgreementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPSpecialEntityElectionAgreementDate(String value) {
        this.ecpSpecialEntityElectionAgreementDate = value;
    }

    /**
     * Gets the value of the nonSpecialEntityTradingLetterAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonSpecialEntityTradingLetterAgreement() {
        return nonSpecialEntityTradingLetterAgreement;
    }

    /**
     * Sets the value of the nonSpecialEntityTradingLetterAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonSpecialEntityTradingLetterAgreement(String value) {
        this.nonSpecialEntityTradingLetterAgreement = value;
    }

    /**
     * Gets the value of the nonSpecialEntityTradingLetterAgreementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonSpecialEntityTradingLetterAgreementDate() {
        return nonSpecialEntityTradingLetterAgreementDate;
    }

    /**
     * Sets the value of the nonSpecialEntityTradingLetterAgreementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonSpecialEntityTradingLetterAgreementDate(String value) {
        this.nonSpecialEntityTradingLetterAgreementDate = value;
    }

    /**
     * Gets the value of the institutionSuitabilityAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionSuitabilityAgreement() {
        return institutionSuitabilityAgreement;
    }

    /**
     * Sets the value of the institutionSuitabilityAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionSuitabilityAgreement(String value) {
        this.institutionSuitabilityAgreement = value;
    }

    /**
     * Gets the value of the institutionSuitabilityAgreementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionSuitabilityAgreementDate() {
        return institutionSuitabilityAgreementDate;
    }

    /**
     * Sets the value of the institutionSuitabilityAgreementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionSuitabilityAgreementDate(String value) {
        this.institutionSuitabilityAgreementDate = value;
    }

    /**
     * Gets the value of the specialEntityTradingLetterAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialEntityTradingLetterAgreement() {
        return specialEntityTradingLetterAgreement;
    }

    /**
     * Sets the value of the specialEntityTradingLetterAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialEntityTradingLetterAgreement(String value) {
        this.specialEntityTradingLetterAgreement = value;
    }

    /**
     * Gets the value of the specialEntityTradingLetterAgreementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialEntityTradingLetterAgreementDate() {
        return specialEntityTradingLetterAgreementDate;
    }

    /**
     * Sets the value of the specialEntityTradingLetterAgreementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialEntityTradingLetterAgreementDate(String value) {
        this.specialEntityTradingLetterAgreementDate = value;
    }

    /**
     * Gets the value of the negativeConsentLetterRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegativeConsentLetterRequired() {
        return negativeConsentLetterRequired;
    }

    /**
     * Sets the value of the negativeConsentLetterRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegativeConsentLetterRequired(String value) {
        this.negativeConsentLetterRequired = value;
    }

    /**
     * Gets the value of the negativeConsentLetterSentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegativeConsentLetterSentDate() {
        return negativeConsentLetterSentDate;
    }

    /**
     * Sets the value of the negativeConsentLetterSentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegativeConsentLetterSentDate(String value) {
        this.negativeConsentLetterSentDate = value;
    }

    /**
     * Gets the value of the disclosuresProvided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclosuresProvided() {
        return disclosuresProvided;
    }

    /**
     * Sets the value of the disclosuresProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclosuresProvided(String value) {
        this.disclosuresProvided = value;
    }

    /**
     * Gets the value of the disclosuresProvidedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclosuresProvidedDate() {
        return disclosuresProvidedDate;
    }

    /**
     * Sets the value of the disclosuresProvidedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclosuresProvidedDate(String value) {
        this.disclosuresProvidedDate = value;
    }

    /**
     * Gets the value of the deliveryMechanismOfDisclosures property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryMechanismOfDisclosures() {
        return deliveryMechanismOfDisclosures;
    }

    /**
     * Sets the value of the deliveryMechanismOfDisclosures property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryMechanismOfDisclosures(String value) {
        this.deliveryMechanismOfDisclosures = value;
    }

    /**
     * Gets the value of the protocol2AdherenceLetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol2AdherenceLetter() {
        return protocol2AdherenceLetter;
    }

    /**
     * Sets the value of the protocol2AdherenceLetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol2AdherenceLetter(String value) {
        this.protocol2AdherenceLetter = value;
    }

    /**
     * Gets the value of the adherenceLetterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdherenceLetterID() {
        return adherenceLetterID;
    }

    /**
     * Sets the value of the adherenceLetterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdherenceLetterID(String value) {
        this.adherenceLetterID = value;
    }

    /**
     * Gets the value of the secIssuerFiler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECIssuerFiler() {
        return secIssuerFiler;
    }

    /**
     * Sets the value of the secIssuerFiler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECIssuerFiler(String value) {
        this.secIssuerFiler = value;
    }

    /**
     * Gets the value of the electionApproval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectionApproval() {
        return electionApproval;
    }

    /**
     * Sets the value of the electionApproval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectionApproval(String value) {
        this.electionApproval = value;
    }

    /**
     * Gets the value of the cftcSwapEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCFTCSwapEntity() {
        return cftcSwapEntity;
    }

    /**
     * Sets the value of the cftcSwapEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCFTCSwapEntity(String value) {
        this.cftcSwapEntity = value;
    }

    /**
     * Gets the value of the financialEntity20 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialEntity20() {
        return financialEntity20;
    }

    /**
     * Sets the value of the financialEntity20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialEntity20(String value) {
        this.financialEntity20 = value;
    }

    /**
     * Gets the value of the financialCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialCompany() {
        return financialCompany;
    }

    /**
     * Sets the value of the financialCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialCompany(String value) {
        this.financialCompany = value;
    }

    /**
     * Gets the value of the insuredDepositoryInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredDepositoryInstitution() {
        return insuredDepositoryInstitution;
    }

    /**
     * Sets the value of the insuredDepositoryInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredDepositoryInstitution(String value) {
        this.insuredDepositoryInstitution = value;
    }

    /**
     * Gets the value of the deliveryOfNoticesEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryOfNoticesEmail() {
        return deliveryOfNoticesEmail;
    }

    /**
     * Sets the value of the deliveryOfNoticesEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryOfNoticesEmail(String value) {
        this.deliveryOfNoticesEmail = value;
    }

    /**
     * Gets the value of the riskValuationsEmai property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskValuationsEmai() {
        return riskValuationsEmai;
    }

    /**
     * Sets the value of the riskValuationsEmai property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskValuationsEmai(String value) {
        this.riskValuationsEmai = value;
    }

    /**
     * Gets the value of the portfolioDataEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioDataEmail() {
        return portfolioDataEmail;
    }

    /**
     * Sets the value of the portfolioDataEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioDataEmail(String value) {
        this.portfolioDataEmail = value;
    }

    /**
     * Gets the value of the localBusinessDayCityOrCities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalBusinessDayCityOrCities() {
        return localBusinessDayCityOrCities;
    }

    /**
     * Sets the value of the localBusinessDayCityOrCities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalBusinessDayCityOrCities(String value) {
        this.localBusinessDayCityOrCities = value;
    }

    /**
     * Gets the value of the protocol20Schedules property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol20Schedules() {
        return protocol20Schedules;
    }

    /**
     * Sets the value of the protocol20Schedules property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol20Schedules(String value) {
        this.protocol20Schedules = value;
    }

    /**
     * Gets the value of the march2013DFMasterAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarch2013DFMasterAgreement() {
        return march2013DFMasterAgreement;
    }

    /**
     * Sets the value of the march2013DFMasterAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarch2013DFMasterAgreement(String value) {
        this.march2013DFMasterAgreement = value;
    }

    /**
     * Gets the value of the reviewExchangePortfolioData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewExchangePortfolioData() {
        return reviewExchangePortfolioData;
    }

    /**
     * Sets the value of the reviewExchangePortfolioData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewExchangePortfolioData(String value) {
        this.reviewExchangePortfolioData = value;
    }

    /**
     * Gets the value of the agreeToReconcileSDRData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreeToReconcileSDRData() {
        return agreeToReconcileSDRData;
    }

    /**
     * Sets the value of the agreeToReconcileSDRData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreeToReconcileSDRData(String value) {
        this.agreeToReconcileSDRData = value;
    }

    /**
     * Gets the value of the standingEndUserExemption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandingEndUserExemption() {
        return standingEndUserExemption;
    }

    /**
     * Sets the value of the standingEndUserExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandingEndUserExemption(String value) {
        this.standingEndUserExemption = value;
    }

    /**
     * Gets the value of the standingOptOutOfAnnualFiling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandingOptOutOfAnnualFiling() {
        return standingOptOutOfAnnualFiling;
    }

    /**
     * Sets the value of the standingOptOutOfAnnualFiling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandingOptOutOfAnnualFiling(String value) {
        this.standingOptOutOfAnnualFiling = value;
    }

    /**
     * Gets the value of the financeAffiliateExemption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinanceAffiliateExemption() {
        return financeAffiliateExemption;
    }

    /**
     * Sets the value of the financeAffiliateExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinanceAffiliateExemption(String value) {
        this.financeAffiliateExemption = value;
    }

    /**
     * Gets the value of the hedgingAffiliateExemption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHedgingAffiliateExemption() {
        return hedgingAffiliateExemption;
    }

    /**
     * Sets the value of the hedgingAffiliateExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHedgingAffiliateExemption(String value) {
        this.hedgingAffiliateExemption = value;
    }

    /**
     * Gets the value of the smallBankExemption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmallBankExemption() {
        return smallBankExemption;
    }

    /**
     * Sets the value of the smallBankExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmallBankExemption(String value) {
        this.smallBankExemption = value;
    }

    /**
     * Gets the value of the unclearedSwapFinancialObligations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnclearedSwapFinancialObligations() {
        return unclearedSwapFinancialObligations;
    }

    /**
     * Sets the value of the unclearedSwapFinancialObligations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnclearedSwapFinancialObligations(String value) {
        this.unclearedSwapFinancialObligations = value;
    }

    /**
     * Gets the value of the usPersonRepresentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPersonRepresentation() {
        return usPersonRepresentation;
    }

    /**
     * Sets the value of the usPersonRepresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPersonRepresentation(String value) {
        this.usPersonRepresentation = value;
    }

    /**
     * Gets the value of the affiliateConduitRepresentations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliateConduitRepresentations() {
        return affiliateConduitRepresentations;
    }

    /**
     * Sets the value of the affiliateConduitRepresentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliateConduitRepresentations(String value) {
        this.affiliateConduitRepresentations = value;
    }

    /**
     * Gets the value of the guaranteeRepresentationsGeneral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuaranteeRepresentationsGeneral() {
        return guaranteeRepresentationsGeneral;
    }

    /**
     * Sets the value of the guaranteeRepresentationsGeneral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuaranteeRepresentationsGeneral(String value) {
        this.guaranteeRepresentationsGeneral = value;
    }

    /**
     * Gets the value of the financialEntityGuarantees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialEntityGuarantees() {
        return financialEntityGuarantees;
    }

    /**
     * Sets the value of the financialEntityGuarantees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialEntityGuarantees(String value) {
        this.financialEntityGuarantees = value;
    }

    /**
     * Gets the value of the swapDealerAffiliateGuarantees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwapDealerAffiliateGuarantees() {
        return swapDealerAffiliateGuarantees;
    }

    /**
     * Sets the value of the swapDealerAffiliateGuarantees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwapDealerAffiliateGuarantees(String value) {
        this.swapDealerAffiliateGuarantees = value;
    }

    /**
     * Gets the value of the writtenAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrittenAgreement() {
        return writtenAgreement;
    }

    /**
     * Sets the value of the writtenAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrittenAgreement(String value) {
        this.writtenAgreement = value;
    }

    /**
     * Gets the value of the dateOfWrittenAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfWrittenAgreement() {
        return dateOfWrittenAgreement;
    }

    /**
     * Sets the value of the dateOfWrittenAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfWrittenAgreement(String value) {
        this.dateOfWrittenAgreement = value;
    }

    /**
     * Gets the value of the reconType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReconType() {
        return reconType;
    }

    /**
     * Sets the value of the reconType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReconType(String value) {
        this.reconType = value;
    }

    /**
     * Gets the value of the substitutedCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstitutedCompliance() {
        return substitutedCompliance;
    }

    /**
     * Sets the value of the substitutedCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstitutedCompliance(String value) {
        this.substitutedCompliance = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
