//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EMIR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EMIR">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}EMIRAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EMIR")
public class EMIR
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "EMIRClassification", required = true)
    protected String emirClassification;
    @XmlAttribute(name = "EMIRClearingCategory", required = true)
    protected String emirClearingCategory;
    @XmlAttribute(name = "ExemptFromClearingType", required = true)
    protected String exemptFromClearingType;
    @XmlAttribute(name = "ExemptionComments", required = true)
    protected String exemptionComments;
    @XmlAttribute(name = "LegalEntityName")
    protected String legalEntityName;
    @XmlAttribute(name = "BankingGroup")
    protected String bankingGroup;
    @XmlAttribute(name = "LEI")
    protected String lei;
    @XmlAttribute(name = "BusinessLine")
    protected String businessLine;
    @XmlAttribute(name = "LegalEntityType")
    protected String legalEntityType;
    @XmlAttribute(name = "DesignatedBusinessLine")
    protected String designatedBusinessLine;
    @XmlAttribute(name = "CountryOfIncorporation")
    protected String countryOfIncorporation;
    @XmlAttribute(name = "RestrictedTradingSystems")
    protected String restrictedTradingSystems;
    @XmlAttribute(name = "NAICCode")
    protected String naicCode;
    @XmlAttribute(name = "SICCode")
    protected String sicCode;
    @XmlAttribute(name = "RegulatedBy")
    protected String regulatedBy;
    @XmlAttribute(name = "ClientContact")
    protected String clientContact;
    @XmlAttribute(name = "EMIRComplainceStatus")
    protected String emirComplainceStatus;
    @XmlAttribute(name = "ExemptFromClearing")
    protected String exemptFromClearing;
    @XmlAttribute(name = "AlternativeInvestmentFund")
    protected String alternativeInvestmentFund;
    @XmlAttribute(name = "TypeOfPensionSchemeArrangement")
    protected String typeOfPensionSchemeArrangement;
    @XmlAttribute(name = "UseOfPensionSchemeArrangementExemption")
    protected String useOfPensionSchemeArrangementExemption;
    @XmlAttribute(name = "EMIRStatus")
    protected String emirStatus;
    @XmlAttribute(name = "EMIRStatusOptions")
    protected String emirStatusOptions;
    @XmlAttribute(name = "WrittenAgreement")
    protected String writtenAgreement;
    @XmlAttribute(name = "DateOfWrittenAgreement")
    protected String dateOfWrittenAgreement;
    @XmlAttribute(name = "ReconciliationType")
    protected String reconciliationType;
    @XmlAttribute(name = "SubstitutedCompliance")
    protected String substitutedCompliance;
    @XmlAttribute(name = "EMIRProceduresAgreed")
    protected String emirProceduresAgreed;
    @XmlAttribute(name = "EEACounterparty")
    protected String eeaCounterparty;
    @XmlAttribute(name = "ISDAStatus")
    protected String isdaStatus;
    @XmlAttribute(name = "InternalOnlyCounterParty")
    protected String internalOnlyCounterParty;
    @XmlAttribute(name = "MasterAgreementType")
    protected String masterAgreementType;
    @XmlAttribute(name = "PortfolioReconciliation")
    protected String portfolioReconciliation;
    @XmlAttribute(name = "EMIRISDAProtocolAdherence")
    protected String emirisdaProtocolAdherence;
    @XmlAttribute(name = "ClearingThresholdExceeded")
    protected String clearingThresholdExceeded;
    @XmlAttribute(name = "EMIRDocumentation")
    protected String emirDocumentation;
    @XmlAttribute(name = "AssignedTeam")
    protected String assignedTeam;
    @XmlAttribute(name = "PortfolioData")
    protected String portfolioData;
    @XmlAttribute(name = "DelegatedReporting")
    protected String delegatedReporting;
    @XmlAttribute(name = "BICClientCode")
    protected String bicClientCode;
    @XmlAttribute(name = "DelegatedTo")
    protected String delegatedTo;

    /**
     * Gets the value of the emirClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRClassification() {
        return emirClassification;
    }

    /**
     * Sets the value of the emirClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRClassification(String value) {
        this.emirClassification = value;
    }

    /**
     * Gets the value of the emirClearingCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRClearingCategory() {
        return emirClearingCategory;
    }

    /**
     * Sets the value of the emirClearingCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRClearingCategory(String value) {
        this.emirClearingCategory = value;
    }

    /**
     * Gets the value of the exemptFromClearingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptFromClearingType() {
        return exemptFromClearingType;
    }

    /**
     * Sets the value of the exemptFromClearingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptFromClearingType(String value) {
        this.exemptFromClearingType = value;
    }

    /**
     * Gets the value of the exemptionComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptionComments() {
        return exemptionComments;
    }

    /**
     * Sets the value of the exemptionComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptionComments(String value) {
        this.exemptionComments = value;
    }

    /**
     * Gets the value of the legalEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityName() {
        return legalEntityName;
    }

    /**
     * Sets the value of the legalEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityName(String value) {
        this.legalEntityName = value;
    }

    /**
     * Gets the value of the bankingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankingGroup() {
        return bankingGroup;
    }

    /**
     * Sets the value of the bankingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankingGroup(String value) {
        this.bankingGroup = value;
    }

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the businessLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessLine() {
        return businessLine;
    }

    /**
     * Sets the value of the businessLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessLine(String value) {
        this.businessLine = value;
    }

    /**
     * Gets the value of the legalEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityType() {
        return legalEntityType;
    }

    /**
     * Sets the value of the legalEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityType(String value) {
        this.legalEntityType = value;
    }

    /**
     * Gets the value of the designatedBusinessLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignatedBusinessLine() {
        return designatedBusinessLine;
    }

    /**
     * Sets the value of the designatedBusinessLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignatedBusinessLine(String value) {
        this.designatedBusinessLine = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the restrictedTradingSystems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictedTradingSystems() {
        return restrictedTradingSystems;
    }

    /**
     * Sets the value of the restrictedTradingSystems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictedTradingSystems(String value) {
        this.restrictedTradingSystems = value;
    }

    /**
     * Gets the value of the naicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICCode() {
        return naicCode;
    }

    /**
     * Sets the value of the naicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICCode(String value) {
        this.naicCode = value;
    }

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSICCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSICCode(String value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the regulatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatedBy() {
        return regulatedBy;
    }

    /**
     * Sets the value of the regulatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatedBy(String value) {
        this.regulatedBy = value;
    }

    /**
     * Gets the value of the clientContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientContact() {
        return clientContact;
    }

    /**
     * Sets the value of the clientContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientContact(String value) {
        this.clientContact = value;
    }

    /**
     * Gets the value of the emirComplainceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRComplainceStatus() {
        return emirComplainceStatus;
    }

    /**
     * Sets the value of the emirComplainceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRComplainceStatus(String value) {
        this.emirComplainceStatus = value;
    }

    /**
     * Gets the value of the exemptFromClearing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptFromClearing() {
        return exemptFromClearing;
    }

    /**
     * Sets the value of the exemptFromClearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptFromClearing(String value) {
        this.exemptFromClearing = value;
    }

    /**
     * Gets the value of the alternativeInvestmentFund property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternativeInvestmentFund() {
        return alternativeInvestmentFund;
    }

    /**
     * Sets the value of the alternativeInvestmentFund property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternativeInvestmentFund(String value) {
        this.alternativeInvestmentFund = value;
    }

    /**
     * Gets the value of the typeOfPensionSchemeArrangement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfPensionSchemeArrangement() {
        return typeOfPensionSchemeArrangement;
    }

    /**
     * Sets the value of the typeOfPensionSchemeArrangement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfPensionSchemeArrangement(String value) {
        this.typeOfPensionSchemeArrangement = value;
    }

    /**
     * Gets the value of the useOfPensionSchemeArrangementExemption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseOfPensionSchemeArrangementExemption() {
        return useOfPensionSchemeArrangementExemption;
    }

    /**
     * Sets the value of the useOfPensionSchemeArrangementExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseOfPensionSchemeArrangementExemption(String value) {
        this.useOfPensionSchemeArrangementExemption = value;
    }

    /**
     * Gets the value of the emirStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRStatus() {
        return emirStatus;
    }

    /**
     * Sets the value of the emirStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRStatus(String value) {
        this.emirStatus = value;
    }

    /**
     * Gets the value of the emirStatusOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRStatusOptions() {
        return emirStatusOptions;
    }

    /**
     * Sets the value of the emirStatusOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRStatusOptions(String value) {
        this.emirStatusOptions = value;
    }

    /**
     * Gets the value of the writtenAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWrittenAgreement() {
        return writtenAgreement;
    }

    /**
     * Sets the value of the writtenAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWrittenAgreement(String value) {
        this.writtenAgreement = value;
    }

    /**
     * Gets the value of the dateOfWrittenAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfWrittenAgreement() {
        return dateOfWrittenAgreement;
    }

    /**
     * Sets the value of the dateOfWrittenAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfWrittenAgreement(String value) {
        this.dateOfWrittenAgreement = value;
    }

    /**
     * Gets the value of the reconciliationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReconciliationType() {
        return reconciliationType;
    }

    /**
     * Sets the value of the reconciliationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReconciliationType(String value) {
        this.reconciliationType = value;
    }

    /**
     * Gets the value of the substitutedCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstitutedCompliance() {
        return substitutedCompliance;
    }

    /**
     * Sets the value of the substitutedCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstitutedCompliance(String value) {
        this.substitutedCompliance = value;
    }

    /**
     * Gets the value of the emirProceduresAgreed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRProceduresAgreed() {
        return emirProceduresAgreed;
    }

    /**
     * Sets the value of the emirProceduresAgreed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRProceduresAgreed(String value) {
        this.emirProceduresAgreed = value;
    }

    /**
     * Gets the value of the eeaCounterparty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEEACounterparty() {
        return eeaCounterparty;
    }

    /**
     * Sets the value of the eeaCounterparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEEACounterparty(String value) {
        this.eeaCounterparty = value;
    }

    /**
     * Gets the value of the isdaStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDAStatus() {
        return isdaStatus;
    }

    /**
     * Sets the value of the isdaStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDAStatus(String value) {
        this.isdaStatus = value;
    }

    /**
     * Gets the value of the internalOnlyCounterParty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalOnlyCounterParty() {
        return internalOnlyCounterParty;
    }

    /**
     * Sets the value of the internalOnlyCounterParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalOnlyCounterParty(String value) {
        this.internalOnlyCounterParty = value;
    }

    /**
     * Gets the value of the masterAgreementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterAgreementType() {
        return masterAgreementType;
    }

    /**
     * Sets the value of the masterAgreementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterAgreementType(String value) {
        this.masterAgreementType = value;
    }

    /**
     * Gets the value of the portfolioReconciliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioReconciliation() {
        return portfolioReconciliation;
    }

    /**
     * Sets the value of the portfolioReconciliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioReconciliation(String value) {
        this.portfolioReconciliation = value;
    }

    /**
     * Gets the value of the emirisdaProtocolAdherence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRISDAProtocolAdherence() {
        return emirisdaProtocolAdherence;
    }

    /**
     * Sets the value of the emirisdaProtocolAdherence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRISDAProtocolAdherence(String value) {
        this.emirisdaProtocolAdherence = value;
    }

    /**
     * Gets the value of the clearingThresholdExceeded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearingThresholdExceeded() {
        return clearingThresholdExceeded;
    }

    /**
     * Sets the value of the clearingThresholdExceeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearingThresholdExceeded(String value) {
        this.clearingThresholdExceeded = value;
    }

    /**
     * Gets the value of the emirDocumentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMIRDocumentation() {
        return emirDocumentation;
    }

    /**
     * Sets the value of the emirDocumentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMIRDocumentation(String value) {
        this.emirDocumentation = value;
    }

    /**
     * Gets the value of the assignedTeam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedTeam() {
        return assignedTeam;
    }

    /**
     * Sets the value of the assignedTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedTeam(String value) {
        this.assignedTeam = value;
    }

    /**
     * Gets the value of the portfolioData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioData() {
        return portfolioData;
    }

    /**
     * Sets the value of the portfolioData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioData(String value) {
        this.portfolioData = value;
    }

    /**
     * Gets the value of the delegatedReporting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegatedReporting() {
        return delegatedReporting;
    }

    /**
     * Sets the value of the delegatedReporting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegatedReporting(String value) {
        this.delegatedReporting = value;
    }

    /**
     * Gets the value of the bicClientCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBICClientCode() {
        return bicClientCode;
    }

    /**
     * Sets the value of the bicClientCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBICClientCode(String value) {
        this.bicClientCode = value;
    }

    /**
     * Gets the value of the delegatedTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegatedTo() {
        return delegatedTo;
    }

    /**
     * Sets the value of the delegatedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegatedTo(String value) {
        this.delegatedTo = value;
    }

}
