//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FATCATAX complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FATCATAX">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}FATCATAXAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FATCATAX")
public class FATCATAX
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "TaxAnalysisBasedOn", required = true)
    protected String taxAnalysisBasedOn;
    @XmlAttribute(name = "FATCAEntityType", required = true)
    protected String fatcaEntityType;
    @XmlAttribute(name = "FATCAEntityStatus", required = true)
    protected String fatcaEntityStatus;
    @XmlAttribute(name = "FATCAStatus", required = true)
    protected String fatcaStatus;
    @XmlAttribute(name = "PleaseSpecifyOther", required = true)
    protected String pleaseSpecifyOther;
    @XmlAttribute(name = "CRSExemptionType", required = true)
    protected String crsExemptionType;
    @XmlAttribute(name = "LegalEntityName")
    protected String legalEntityName;
    @XmlAttribute(name = "LegalEntityType")
    protected String legalEntityType;
    @XmlAttribute(name = "TAXID")
    protected String taxid;
    @XmlAttribute(name = "TAXIDNumber")
    protected String taxidNumber;
    @XmlAttribute(name = "LegalStatus")
    protected String legalStatus;
    @XmlAttribute(name = "NAICCode")
    protected String naicCode;
    @XmlAttribute(name = "NAICCodeNumber")
    protected String naicCodeNumber;
    @XmlAttribute(name = "PrimaryBusinessLoc")
    protected String primaryBusinessLoc;
    @XmlAttribute(name = "DateOfBirthNotPresentForCompany")
    protected String dateOfBirthNotPresentForCompany;
    @XmlAttribute(name = "BusinessMarkets")
    protected String businessMarkets;
    @XmlAttribute(name = "NationalityNotPresentForCompany")
    protected String nationalityNotPresentForCompany;
    @XmlAttribute(name = "StockExchange")
    protected String stockExchange;
    @XmlAttribute(name = "CountryOfIncorporation")
    protected String countryOfIncorporation;
    @XmlAttribute(name = "TaxIDClassificationCode")
    protected String taxIDClassificationCode;
    @XmlAttribute(name = "TaxIDClassification")
    protected String taxIDClassification;
    @XmlAttribute(name = "GIIN")
    protected String giin;
    @XmlAttribute(name = "USTaxExempt")
    protected String usTaxExempt;
    @XmlAttribute(name = "QualifiedIntermediary")
    protected String qualifiedIntermediary;
    @XmlAttribute(name = "EntityOwnershipStatus")
    protected String entityOwnershipStatus;
    @XmlAttribute(name = "ConnectedWithATradeOrBusinessInBusinessInTheUnitedStates")
    protected String connectedWithATradeOrBusinessInBusinessInTheUnitedStates;
    @XmlAttribute(name = "USSubstantialControllingPersons")
    protected String usSubstantialControllingPersons;
    @XmlAttribute(name = "USBranchElections")
    protected String usBranchElections;
    @XmlAttribute(name = "DepositAndCustodialAccount")
    protected String depositAndCustodialAccount;
    @XmlAttribute(name = "NonWithholdingPartnershipSimpleTrustOrGrantorTrustElection")
    protected String nonWithholdingPartnershipSimpleTrustOrGrantorTrustElection;
    @XmlAttribute(name = "ForeignPartnershipTrustElections")
    protected String foreignPartnershipTrustElections;
    @XmlAttribute(name = "RecommendedFATCAWithholding")
    protected String recommendedFATCAWithholding;
    @XmlAttribute(name = "FATCAID")
    protected String fatcaid;
    @XmlAttribute(name = "ExemptionComments")
    protected String exemptionComments;
    @XmlAttribute(name = "FormW9ExemptionFormFATCAReportingCode")
    protected String formW9ExemptionFormFATCAReportingCode;
    @XmlAttribute(name = "FormW9ExemptPayeeCode")
    protected String formW9ExemptPayeeCode;
    @XmlAttribute(name = "W8IMYEffectiveRateOfWithholdingWorksheet")
    protected String w8IMYEffectiveRateOfWithholdingWorksheet;
    @XmlAttribute(name = "FATCAUSPerson")
    protected String fatcausPerson;
    @XmlAttribute(name = "Reportable")
    protected String reportable;
    @XmlAttribute(name = "Ch3FederalTaxClassification")
    protected String ch3FederalTaxClassification;
    @XmlAttribute(name = "_1099MISCFlag")
    protected String _1099MISCFlag;
    @XmlAttribute(name = "_1042SFlag")
    protected String _1042SFlag;
    @XmlAttribute(name = "EntityType")
    protected String entityType;
    @XmlAttribute(name = "CRSExempt")
    protected String crsExempt;
    @XmlAttribute(name = "HighValueAccount")
    protected String highValueAccount;
    @XmlAttribute(name = "SoleTaxResidency")
    protected String soleTaxResidency;
    @XmlAttribute(name = "PTRSNo")
    protected String ptrsNo;
    @XmlAttribute(name = "TaxFormProvided")
    protected String taxFormProvided;
    @XmlAttribute(name = "TaxFormType")
    protected String taxFormType;
    @XmlAttribute(name = "TaxDocumentStatus")
    protected String taxDocumentStatus;
    @XmlAttribute(name = "TaxFormExpiryDate")
    protected String taxFormExpiryDate;
    @XmlAttribute(name = "ISDAFATCAProtocol")
    protected String isdafatcaProtocol;

    /**
     * Gets the value of the taxAnalysisBasedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAnalysisBasedOn() {
        return taxAnalysisBasedOn;
    }

    /**
     * Sets the value of the taxAnalysisBasedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAnalysisBasedOn(String value) {
        this.taxAnalysisBasedOn = value;
    }

    /**
     * Gets the value of the fatcaEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCAEntityType() {
        return fatcaEntityType;
    }

    /**
     * Sets the value of the fatcaEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCAEntityType(String value) {
        this.fatcaEntityType = value;
    }

    /**
     * Gets the value of the fatcaEntityStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCAEntityStatus() {
        return fatcaEntityStatus;
    }

    /**
     * Sets the value of the fatcaEntityStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCAEntityStatus(String value) {
        this.fatcaEntityStatus = value;
    }

    /**
     * Gets the value of the fatcaStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCAStatus() {
        return fatcaStatus;
    }

    /**
     * Sets the value of the fatcaStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCAStatus(String value) {
        this.fatcaStatus = value;
    }

    /**
     * Gets the value of the pleaseSpecifyOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPleaseSpecifyOther() {
        return pleaseSpecifyOther;
    }

    /**
     * Sets the value of the pleaseSpecifyOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPleaseSpecifyOther(String value) {
        this.pleaseSpecifyOther = value;
    }

    /**
     * Gets the value of the crsExemptionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRSExemptionType() {
        return crsExemptionType;
    }

    /**
     * Sets the value of the crsExemptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRSExemptionType(String value) {
        this.crsExemptionType = value;
    }

    /**
     * Gets the value of the legalEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityName() {
        return legalEntityName;
    }

    /**
     * Sets the value of the legalEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityName(String value) {
        this.legalEntityName = value;
    }

    /**
     * Gets the value of the legalEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityType() {
        return legalEntityType;
    }

    /**
     * Sets the value of the legalEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityType(String value) {
        this.legalEntityType = value;
    }

    /**
     * Gets the value of the taxid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXID() {
        return taxid;
    }

    /**
     * Sets the value of the taxid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXID(String value) {
        this.taxid = value;
    }

    /**
     * Gets the value of the taxidNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAXIDNumber() {
        return taxidNumber;
    }

    /**
     * Sets the value of the taxidNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAXIDNumber(String value) {
        this.taxidNumber = value;
    }

    /**
     * Gets the value of the legalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalStatus() {
        return legalStatus;
    }

    /**
     * Sets the value of the legalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalStatus(String value) {
        this.legalStatus = value;
    }

    /**
     * Gets the value of the naicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICCode() {
        return naicCode;
    }

    /**
     * Sets the value of the naicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICCode(String value) {
        this.naicCode = value;
    }

    /**
     * Gets the value of the naicCodeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICCodeNumber() {
        return naicCodeNumber;
    }

    /**
     * Sets the value of the naicCodeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICCodeNumber(String value) {
        this.naicCodeNumber = value;
    }

    /**
     * Gets the value of the primaryBusinessLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryBusinessLoc() {
        return primaryBusinessLoc;
    }

    /**
     * Sets the value of the primaryBusinessLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryBusinessLoc(String value) {
        this.primaryBusinessLoc = value;
    }

    /**
     * Gets the value of the dateOfBirthNotPresentForCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirthNotPresentForCompany() {
        return dateOfBirthNotPresentForCompany;
    }

    /**
     * Sets the value of the dateOfBirthNotPresentForCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirthNotPresentForCompany(String value) {
        this.dateOfBirthNotPresentForCompany = value;
    }

    /**
     * Gets the value of the businessMarkets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessMarkets() {
        return businessMarkets;
    }

    /**
     * Sets the value of the businessMarkets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessMarkets(String value) {
        this.businessMarkets = value;
    }

    /**
     * Gets the value of the nationalityNotPresentForCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationalityNotPresentForCompany() {
        return nationalityNotPresentForCompany;
    }

    /**
     * Sets the value of the nationalityNotPresentForCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationalityNotPresentForCompany(String value) {
        this.nationalityNotPresentForCompany = value;
    }

    /**
     * Gets the value of the stockExchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStockExchange() {
        return stockExchange;
    }

    /**
     * Sets the value of the stockExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStockExchange(String value) {
        this.stockExchange = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the taxIDClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIDClassificationCode() {
        return taxIDClassificationCode;
    }

    /**
     * Sets the value of the taxIDClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIDClassificationCode(String value) {
        this.taxIDClassificationCode = value;
    }

    /**
     * Gets the value of the taxIDClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIDClassification() {
        return taxIDClassification;
    }

    /**
     * Sets the value of the taxIDClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIDClassification(String value) {
        this.taxIDClassification = value;
    }

    /**
     * Gets the value of the giin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGIIN() {
        return giin;
    }

    /**
     * Sets the value of the giin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGIIN(String value) {
        this.giin = value;
    }

    /**
     * Gets the value of the usTaxExempt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSTaxExempt() {
        return usTaxExempt;
    }

    /**
     * Sets the value of the usTaxExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSTaxExempt(String value) {
        this.usTaxExempt = value;
    }

    /**
     * Gets the value of the qualifiedIntermediary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifiedIntermediary() {
        return qualifiedIntermediary;
    }

    /**
     * Sets the value of the qualifiedIntermediary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifiedIntermediary(String value) {
        this.qualifiedIntermediary = value;
    }

    /**
     * Gets the value of the entityOwnershipStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityOwnershipStatus() {
        return entityOwnershipStatus;
    }

    /**
     * Sets the value of the entityOwnershipStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityOwnershipStatus(String value) {
        this.entityOwnershipStatus = value;
    }

    /**
     * Gets the value of the connectedWithATradeOrBusinessInBusinessInTheUnitedStates property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectedWithATradeOrBusinessInBusinessInTheUnitedStates() {
        return connectedWithATradeOrBusinessInBusinessInTheUnitedStates;
    }

    /**
     * Sets the value of the connectedWithATradeOrBusinessInBusinessInTheUnitedStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectedWithATradeOrBusinessInBusinessInTheUnitedStates(String value) {
        this.connectedWithATradeOrBusinessInBusinessInTheUnitedStates = value;
    }

    /**
     * Gets the value of the usSubstantialControllingPersons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSSubstantialControllingPersons() {
        return usSubstantialControllingPersons;
    }

    /**
     * Sets the value of the usSubstantialControllingPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSSubstantialControllingPersons(String value) {
        this.usSubstantialControllingPersons = value;
    }

    /**
     * Gets the value of the usBranchElections property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSBranchElections() {
        return usBranchElections;
    }

    /**
     * Sets the value of the usBranchElections property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSBranchElections(String value) {
        this.usBranchElections = value;
    }

    /**
     * Gets the value of the depositAndCustodialAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositAndCustodialAccount() {
        return depositAndCustodialAccount;
    }

    /**
     * Sets the value of the depositAndCustodialAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositAndCustodialAccount(String value) {
        this.depositAndCustodialAccount = value;
    }

    /**
     * Gets the value of the nonWithholdingPartnershipSimpleTrustOrGrantorTrustElection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonWithholdingPartnershipSimpleTrustOrGrantorTrustElection() {
        return nonWithholdingPartnershipSimpleTrustOrGrantorTrustElection;
    }

    /**
     * Sets the value of the nonWithholdingPartnershipSimpleTrustOrGrantorTrustElection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonWithholdingPartnershipSimpleTrustOrGrantorTrustElection(String value) {
        this.nonWithholdingPartnershipSimpleTrustOrGrantorTrustElection = value;
    }

    /**
     * Gets the value of the foreignPartnershipTrustElections property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignPartnershipTrustElections() {
        return foreignPartnershipTrustElections;
    }

    /**
     * Sets the value of the foreignPartnershipTrustElections property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignPartnershipTrustElections(String value) {
        this.foreignPartnershipTrustElections = value;
    }

    /**
     * Gets the value of the recommendedFATCAWithholding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendedFATCAWithholding() {
        return recommendedFATCAWithholding;
    }

    /**
     * Sets the value of the recommendedFATCAWithholding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendedFATCAWithholding(String value) {
        this.recommendedFATCAWithholding = value;
    }

    /**
     * Gets the value of the fatcaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCAID() {
        return fatcaid;
    }

    /**
     * Sets the value of the fatcaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCAID(String value) {
        this.fatcaid = value;
    }

    /**
     * Gets the value of the exemptionComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptionComments() {
        return exemptionComments;
    }

    /**
     * Sets the value of the exemptionComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptionComments(String value) {
        this.exemptionComments = value;
    }

    /**
     * Gets the value of the formW9ExemptionFormFATCAReportingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormW9ExemptionFormFATCAReportingCode() {
        return formW9ExemptionFormFATCAReportingCode;
    }

    /**
     * Sets the value of the formW9ExemptionFormFATCAReportingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormW9ExemptionFormFATCAReportingCode(String value) {
        this.formW9ExemptionFormFATCAReportingCode = value;
    }

    /**
     * Gets the value of the formW9ExemptPayeeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormW9ExemptPayeeCode() {
        return formW9ExemptPayeeCode;
    }

    /**
     * Sets the value of the formW9ExemptPayeeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormW9ExemptPayeeCode(String value) {
        this.formW9ExemptPayeeCode = value;
    }

    /**
     * Gets the value of the w8IMYEffectiveRateOfWithholdingWorksheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getW8IMYEffectiveRateOfWithholdingWorksheet() {
        return w8IMYEffectiveRateOfWithholdingWorksheet;
    }

    /**
     * Sets the value of the w8IMYEffectiveRateOfWithholdingWorksheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setW8IMYEffectiveRateOfWithholdingWorksheet(String value) {
        this.w8IMYEffectiveRateOfWithholdingWorksheet = value;
    }

    /**
     * Gets the value of the fatcausPerson property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFATCAUSPerson() {
        return fatcausPerson;
    }

    /**
     * Sets the value of the fatcausPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFATCAUSPerson(String value) {
        this.fatcausPerson = value;
    }

    /**
     * Gets the value of the reportable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportable() {
        return reportable;
    }

    /**
     * Sets the value of the reportable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportable(String value) {
        this.reportable = value;
    }

    /**
     * Gets the value of the ch3FederalTaxClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCh3FederalTaxClassification() {
        return ch3FederalTaxClassification;
    }

    /**
     * Sets the value of the ch3FederalTaxClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCh3FederalTaxClassification(String value) {
        this.ch3FederalTaxClassification = value;
    }

    /**
     * Gets the value of the 1099MISCFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get1099MISCFlag() {
        return _1099MISCFlag;
    }

    /**
     * Sets the value of the 1099MISCFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set1099MISCFlag(String value) {
        this._1099MISCFlag = value;
    }

    /**
     * Gets the value of the 1042SFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get1042SFlag() {
        return _1042SFlag;
    }

    /**
     * Sets the value of the 1042SFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set1042SFlag(String value) {
        this._1042SFlag = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the crsExempt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRSExempt() {
        return crsExempt;
    }

    /**
     * Sets the value of the crsExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRSExempt(String value) {
        this.crsExempt = value;
    }

    /**
     * Gets the value of the highValueAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighValueAccount() {
        return highValueAccount;
    }

    /**
     * Sets the value of the highValueAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighValueAccount(String value) {
        this.highValueAccount = value;
    }

    /**
     * Gets the value of the soleTaxResidency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoleTaxResidency() {
        return soleTaxResidency;
    }

    /**
     * Sets the value of the soleTaxResidency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoleTaxResidency(String value) {
        this.soleTaxResidency = value;
    }

    /**
     * Gets the value of the ptrsNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPTRSNo() {
        return ptrsNo;
    }

    /**
     * Sets the value of the ptrsNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPTRSNo(String value) {
        this.ptrsNo = value;
    }

    /**
     * Gets the value of the taxFormProvided property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxFormProvided() {
        return taxFormProvided;
    }

    /**
     * Sets the value of the taxFormProvided property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxFormProvided(String value) {
        this.taxFormProvided = value;
    }

    /**
     * Gets the value of the taxFormType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxFormType() {
        return taxFormType;
    }

    /**
     * Sets the value of the taxFormType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxFormType(String value) {
        this.taxFormType = value;
    }

    /**
     * Gets the value of the taxDocumentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxDocumentStatus() {
        return taxDocumentStatus;
    }

    /**
     * Sets the value of the taxDocumentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxDocumentStatus(String value) {
        this.taxDocumentStatus = value;
    }

    /**
     * Gets the value of the taxFormExpiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxFormExpiryDate() {
        return taxFormExpiryDate;
    }

    /**
     * Sets the value of the taxFormExpiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxFormExpiryDate(String value) {
        this.taxFormExpiryDate = value;
    }

    /**
     * Gets the value of the isdafatcaProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDAFATCAProtocol() {
        return isdafatcaProtocol;
    }

    /**
     * Sets the value of the isdafatcaProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDAFATCAProtocol(String value) {
        this.isdafatcaProtocol = value;
    }

}
