//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegalEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LegalEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}LegalEntityAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LegalEntity")
public class LegalEntity
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "LegalEntityType", required = true)
    protected String legalEntityType;
    @XmlAttribute(name = "LegalEntityName", required = true)
    protected String legalEntityName;
    @XmlAttribute(name = "CountryOfIncorporation", required = true)
    protected String countryOfIncorporation;
    @XmlAttribute(name = "LegalEntityRole", required = true)
    protected String legalEntityRole;
    @XmlAttribute(name = "TaxId", required = true)
    protected String taxId;
    @XmlAttribute(name = "TaxIdNumber", required = true)
    protected String taxIdNumber;
    @XmlAttribute(name = "BankJurisdiction", required = true)
    protected String bankJurisdiction;
    @XmlAttribute(name = "BankEntity", required = true)
    protected String bankEntity;
    @XmlAttribute(name = "AddressLine1", required = true)
    protected String addressLine1;
    @XmlAttribute(name = "AddressCountry", required = true)
    protected String addressCountry;
    @XmlAttribute(name = "LEI")
    protected String lei;
    @XmlAttribute(name = "PrimaryBusinessActivity")
    protected String primaryBusinessActivity;
    @XmlAttribute(name = "PrimaryBusinessLocation")
    protected String primaryBusinessLocation;
    @XmlAttribute(name = "BusinessMarkets")
    protected String businessMarkets;
    @XmlAttribute(name = "RegulatedBy")
    protected String regulatedBy;
    @XmlAttribute(name = "PublicallyTradedCompany")
    protected String publicallyTradedCompany;
    @XmlAttribute(name = "RegulatoryStatus")
    protected String regulatoryStatus;
    @XmlAttribute(name = "RegulatoryId")
    protected String regulatoryId;
    @XmlAttribute(name = "NameOfPublicallyTradedParent")
    protected String nameOfPublicallyTradedParent;
    @XmlAttribute(name = "ListedOn")
    protected String listedOn;
    @XmlAttribute(name = "Website")
    protected String website;
    @XmlAttribute(name = "PaymentType")
    protected String paymentType;
    @XmlAttribute(name = "PaymentCountries")
    protected String paymentCountries;
    @XmlAttribute(name = "SourceOfFunds")
    protected String sourceOfFunds;
    @XmlAttribute(name = "ISCCode")
    protected String iscCode;
    @XmlAttribute(name = "SICCode")
    protected String sicCode;
    @XmlAttribute(name = "SwiftCode")
    protected String swiftCode;
    @XmlAttribute(name = "NACE2Code")
    protected String nace2Code;
    @XmlAttribute(name = "ClientReference")
    protected String clientReference;
    @XmlAttribute(name = "ISIN")
    protected String isin;
    @XmlAttribute(name = "LegalStatus")
    protected String legalStatus;
    @XmlAttribute(name = "RegistrationNumber")
    protected String registrationNumber;
    @XmlAttribute(name = "TradingStatus")
    protected String tradingStatus;
    @XmlAttribute(name = "PreviousNames")
    protected String previousNames;
    @XmlAttribute(name = "TradingAs")
    protected String tradingAs;
    @XmlAttribute(name = "PreviousNameDate")
    protected String previousNameDate;
    @XmlAttribute(name = "CountryOfDomicile")
    protected String countryOfDomicile;
    @XmlAttribute(name = "DateOfIncorporation")
    protected String dateOfIncorporation;
    @XmlAttribute(name = "Desk")
    protected String desk;
    @XmlAttribute(name = "DFUSPersonType")
    protected String dfusPersonType;
    @XmlAttribute(name = "ERISAPlanInvestor")
    protected String erisaPlanInvestor;
    @XmlAttribute(name = "CreditReviewDate")
    protected String creditReviewDate;
    @XmlAttribute(name = "AnnualReturnDate")
    protected String annualReturnDate;
    @XmlAttribute(name = "NextReviewDate")
    protected String nextReviewDate;
    @XmlAttribute(name = "LastUpdatedBy")
    protected String lastUpdatedBy;
    @XmlAttribute(name = "Private")
    protected String _private;
    @XmlAttribute(name = "PEPSanctions")
    protected String pepSanctions;
    @XmlAttribute(name = "ISICCode")
    protected String isicCode;
    @XmlAttribute(name = "Ticker")
    protected String ticker;
    @XmlAttribute(name = "NAICCode")
    protected String naicCode;
    @XmlAttribute(name = "CIK")
    protected String cik;

    /**
     * Gets the value of the legalEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityType() {
        return legalEntityType;
    }

    /**
     * Sets the value of the legalEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityType(String value) {
        this.legalEntityType = value;
    }

    /**
     * Gets the value of the legalEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityName() {
        return legalEntityName;
    }

    /**
     * Sets the value of the legalEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityName(String value) {
        this.legalEntityName = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the legalEntityRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityRole() {
        return legalEntityRole;
    }

    /**
     * Sets the value of the legalEntityRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityRole(String value) {
        this.legalEntityRole = value;
    }

    /**
     * Gets the value of the taxId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxId() {
        return taxId;
    }

    /**
     * Sets the value of the taxId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxId(String value) {
        this.taxId = value;
    }

    /**
     * Gets the value of the taxIdNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxIdNumber() {
        return taxIdNumber;
    }

    /**
     * Sets the value of the taxIdNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxIdNumber(String value) {
        this.taxIdNumber = value;
    }

    /**
     * Gets the value of the bankJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankJurisdiction() {
        return bankJurisdiction;
    }

    /**
     * Sets the value of the bankJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankJurisdiction(String value) {
        this.bankJurisdiction = value;
    }

    /**
     * Gets the value of the bankEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankEntity() {
        return bankEntity;
    }

    /**
     * Sets the value of the bankEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankEntity(String value) {
        this.bankEntity = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressCountry() {
        return addressCountry;
    }

    /**
     * Sets the value of the addressCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressCountry(String value) {
        this.addressCountry = value;
    }

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the primaryBusinessActivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryBusinessActivity() {
        return primaryBusinessActivity;
    }

    /**
     * Sets the value of the primaryBusinessActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryBusinessActivity(String value) {
        this.primaryBusinessActivity = value;
    }

    /**
     * Gets the value of the primaryBusinessLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryBusinessLocation() {
        return primaryBusinessLocation;
    }

    /**
     * Sets the value of the primaryBusinessLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryBusinessLocation(String value) {
        this.primaryBusinessLocation = value;
    }

    /**
     * Gets the value of the businessMarkets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessMarkets() {
        return businessMarkets;
    }

    /**
     * Sets the value of the businessMarkets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessMarkets(String value) {
        this.businessMarkets = value;
    }

    /**
     * Gets the value of the regulatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatedBy() {
        return regulatedBy;
    }

    /**
     * Sets the value of the regulatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatedBy(String value) {
        this.regulatedBy = value;
    }

    /**
     * Gets the value of the publicallyTradedCompany property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicallyTradedCompany() {
        return publicallyTradedCompany;
    }

    /**
     * Sets the value of the publicallyTradedCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicallyTradedCompany(String value) {
        this.publicallyTradedCompany = value;
    }

    /**
     * Gets the value of the regulatoryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatoryStatus() {
        return regulatoryStatus;
    }

    /**
     * Sets the value of the regulatoryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatoryStatus(String value) {
        this.regulatoryStatus = value;
    }

    /**
     * Gets the value of the regulatoryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatoryId() {
        return regulatoryId;
    }

    /**
     * Sets the value of the regulatoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatoryId(String value) {
        this.regulatoryId = value;
    }

    /**
     * Gets the value of the nameOfPublicallyTradedParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfPublicallyTradedParent() {
        return nameOfPublicallyTradedParent;
    }

    /**
     * Sets the value of the nameOfPublicallyTradedParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfPublicallyTradedParent(String value) {
        this.nameOfPublicallyTradedParent = value;
    }

    /**
     * Gets the value of the listedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListedOn() {
        return listedOn;
    }

    /**
     * Sets the value of the listedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListedOn(String value) {
        this.listedOn = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentType(String value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the paymentCountries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentCountries() {
        return paymentCountries;
    }

    /**
     * Sets the value of the paymentCountries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCountries(String value) {
        this.paymentCountries = value;
    }

    /**
     * Gets the value of the sourceOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOfFunds() {
        return sourceOfFunds;
    }

    /**
     * Sets the value of the sourceOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOfFunds(String value) {
        this.sourceOfFunds = value;
    }

    /**
     * Gets the value of the iscCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISCCode() {
        return iscCode;
    }

    /**
     * Sets the value of the iscCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISCCode(String value) {
        this.iscCode = value;
    }

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSICCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSICCode(String value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the swiftCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwiftCode() {
        return swiftCode;
    }

    /**
     * Sets the value of the swiftCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwiftCode(String value) {
        this.swiftCode = value;
    }

    /**
     * Gets the value of the nace2Code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNACE2Code() {
        return nace2Code;
    }

    /**
     * Sets the value of the nace2Code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNACE2Code(String value) {
        this.nace2Code = value;
    }

    /**
     * Gets the value of the clientReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientReference() {
        return clientReference;
    }

    /**
     * Sets the value of the clientReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientReference(String value) {
        this.clientReference = value;
    }

    /**
     * Gets the value of the isin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISIN() {
        return isin;
    }

    /**
     * Sets the value of the isin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISIN(String value) {
        this.isin = value;
    }

    /**
     * Gets the value of the legalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalStatus() {
        return legalStatus;
    }

    /**
     * Sets the value of the legalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalStatus(String value) {
        this.legalStatus = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the tradingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingStatus() {
        return tradingStatus;
    }

    /**
     * Sets the value of the tradingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingStatus(String value) {
        this.tradingStatus = value;
    }

    /**
     * Gets the value of the previousNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousNames() {
        return previousNames;
    }

    /**
     * Sets the value of the previousNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousNames(String value) {
        this.previousNames = value;
    }

    /**
     * Gets the value of the tradingAs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingAs() {
        return tradingAs;
    }

    /**
     * Sets the value of the tradingAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingAs(String value) {
        this.tradingAs = value;
    }

    /**
     * Gets the value of the previousNameDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousNameDate() {
        return previousNameDate;
    }

    /**
     * Sets the value of the previousNameDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousNameDate(String value) {
        this.previousNameDate = value;
    }

    /**
     * Gets the value of the countryOfDomicile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfDomicile() {
        return countryOfDomicile;
    }

    /**
     * Sets the value of the countryOfDomicile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfDomicile(String value) {
        this.countryOfDomicile = value;
    }

    /**
     * Gets the value of the dateOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfIncorporation() {
        return dateOfIncorporation;
    }

    /**
     * Sets the value of the dateOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfIncorporation(String value) {
        this.dateOfIncorporation = value;
    }

    /**
     * Gets the value of the desk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesk() {
        return desk;
    }

    /**
     * Sets the value of the desk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesk(String value) {
        this.desk = value;
    }

    /**
     * Gets the value of the dfusPersonType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFUSPersonType() {
        return dfusPersonType;
    }

    /**
     * Sets the value of the dfusPersonType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFUSPersonType(String value) {
        this.dfusPersonType = value;
    }

    /**
     * Gets the value of the erisaPlanInvestor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERISAPlanInvestor() {
        return erisaPlanInvestor;
    }

    /**
     * Sets the value of the erisaPlanInvestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERISAPlanInvestor(String value) {
        this.erisaPlanInvestor = value;
    }

    /**
     * Gets the value of the creditReviewDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditReviewDate() {
        return creditReviewDate;
    }

    /**
     * Sets the value of the creditReviewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditReviewDate(String value) {
        this.creditReviewDate = value;
    }

    /**
     * Gets the value of the annualReturnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnualReturnDate() {
        return annualReturnDate;
    }

    /**
     * Sets the value of the annualReturnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnualReturnDate(String value) {
        this.annualReturnDate = value;
    }

    /**
     * Gets the value of the nextReviewDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextReviewDate() {
        return nextReviewDate;
    }

    /**
     * Sets the value of the nextReviewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextReviewDate(String value) {
        this.nextReviewDate = value;
    }

    /**
     * Gets the value of the lastUpdatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * Sets the value of the lastUpdatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedBy(String value) {
        this.lastUpdatedBy = value;
    }

    /**
     * Gets the value of the private property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivate() {
        return _private;
    }

    /**
     * Sets the value of the private property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivate(String value) {
        this._private = value;
    }

    /**
     * Gets the value of the pepSanctions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEPSanctions() {
        return pepSanctions;
    }

    /**
     * Sets the value of the pepSanctions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEPSanctions(String value) {
        this.pepSanctions = value;
    }

    /**
     * Gets the value of the isicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISICCode() {
        return isicCode;
    }

    /**
     * Sets the value of the isicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISICCode(String value) {
        this.isicCode = value;
    }

    /**
     * Gets the value of the ticker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicker() {
        return ticker;
    }

    /**
     * Sets the value of the ticker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicker(String value) {
        this.ticker = value;
    }

    /**
     * Gets the value of the naicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICCode() {
        return naicCode;
    }

    /**
     * Sets the value of the naicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICCode(String value) {
        this.naicCode = value;
    }

    /**
     * Gets the value of the cik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIK() {
        return cik;
    }

    /**
     * Sets the value of the cik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIK(String value) {
        this.cik = value;
    }

}
