//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MexicanDrivatives complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MexicanDrivatives">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}MexicanDrivativesAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MexicanDrivatives")
public class MexicanDrivatives
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "MexicoClassification")
    protected String mexicoClassification;
    @XmlAttribute(name = "ISDAStatus")
    protected String isdaStatus;
    @XmlAttribute(name = "PortfolioData")
    protected String portfolioData;
    @XmlAttribute(name = "ExemptFromClearing")
    protected String exemptFromClearing;
    @XmlAttribute(name = "ExemptFromClearingType")
    protected String exemptFromClearingType;
    @XmlAttribute(name = "ExemptFromClearingComments")
    protected String exemptFromClearingComments;
    @XmlAttribute(name = "LegalEntityName")
    protected String legalEntityName;
    @XmlAttribute(name = "LEI")
    protected String lei;
    @XmlAttribute(name = "LegalEntityType")
    protected String legalEntityType;
    @XmlAttribute(name = "BankingGroup")
    protected String bankingGroup;
    @XmlAttribute(name = "CountryOfIncorporation")
    protected String countryOfIncorporation;
    @XmlAttribute(name = "DesignatedBusinessLine")
    protected String designatedBusinessLine;
    @XmlAttribute(name = "SICCode")
    protected String sicCode;
    @XmlAttribute(name = "NAICCode")
    protected String naicCode;
    @XmlAttribute(name = "RegulatedBy")
    protected String regulatedBy;
    @XmlAttribute(name = "RestrictedTradingSystems")
    protected String restrictedTradingSystems;
    @XmlAttribute(name = "ClientContact")
    protected String clientContact;
    @XmlAttribute(name = "Comments")
    protected String comments;
    @XmlAttribute(name = "InternalOnlyCounterparty")
    protected String internalOnlyCounterparty;
    @XmlAttribute(name = "LocalCounterparty")
    protected String localCounterparty;
    @XmlAttribute(name = "TypeOfMasterAgreement")
    protected String typeOfMasterAgreement;
    @XmlAttribute(name = "PortfolioReconcilliation")
    protected String portfolioReconcilliation;
    @XmlAttribute(name = "MexicoDocumentation")
    protected String mexicoDocumentation;
    @XmlAttribute(name = "DelegatedReporting")
    protected String delegatedReporting;
    @XmlAttribute(name = "MexicoISDAProtocolAdherence")
    protected String mexicoISDAProtocolAdherence;
    @XmlAttribute(name = "SubstitutedCompliance")
    protected String substitutedCompliance;
    @XmlAttribute(name = "BranchIndicator")
    protected String branchIndicator;

    /**
     * Gets the value of the mexicoClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMexicoClassification() {
        return mexicoClassification;
    }

    /**
     * Sets the value of the mexicoClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMexicoClassification(String value) {
        this.mexicoClassification = value;
    }

    /**
     * Gets the value of the isdaStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDAStatus() {
        return isdaStatus;
    }

    /**
     * Sets the value of the isdaStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDAStatus(String value) {
        this.isdaStatus = value;
    }

    /**
     * Gets the value of the portfolioData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioData() {
        return portfolioData;
    }

    /**
     * Sets the value of the portfolioData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioData(String value) {
        this.portfolioData = value;
    }

    /**
     * Gets the value of the exemptFromClearing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptFromClearing() {
        return exemptFromClearing;
    }

    /**
     * Sets the value of the exemptFromClearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptFromClearing(String value) {
        this.exemptFromClearing = value;
    }

    /**
     * Gets the value of the exemptFromClearingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptFromClearingType() {
        return exemptFromClearingType;
    }

    /**
     * Sets the value of the exemptFromClearingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptFromClearingType(String value) {
        this.exemptFromClearingType = value;
    }

    /**
     * Gets the value of the exemptFromClearingComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptFromClearingComments() {
        return exemptFromClearingComments;
    }

    /**
     * Sets the value of the exemptFromClearingComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptFromClearingComments(String value) {
        this.exemptFromClearingComments = value;
    }

    /**
     * Gets the value of the legalEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityName() {
        return legalEntityName;
    }

    /**
     * Sets the value of the legalEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityName(String value) {
        this.legalEntityName = value;
    }

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the legalEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityType() {
        return legalEntityType;
    }

    /**
     * Sets the value of the legalEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityType(String value) {
        this.legalEntityType = value;
    }

    /**
     * Gets the value of the bankingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankingGroup() {
        return bankingGroup;
    }

    /**
     * Sets the value of the bankingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankingGroup(String value) {
        this.bankingGroup = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the designatedBusinessLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignatedBusinessLine() {
        return designatedBusinessLine;
    }

    /**
     * Sets the value of the designatedBusinessLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignatedBusinessLine(String value) {
        this.designatedBusinessLine = value;
    }

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSICCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSICCode(String value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the naicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNAICCode() {
        return naicCode;
    }

    /**
     * Sets the value of the naicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNAICCode(String value) {
        this.naicCode = value;
    }

    /**
     * Gets the value of the regulatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatedBy() {
        return regulatedBy;
    }

    /**
     * Sets the value of the regulatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatedBy(String value) {
        this.regulatedBy = value;
    }

    /**
     * Gets the value of the restrictedTradingSystems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestrictedTradingSystems() {
        return restrictedTradingSystems;
    }

    /**
     * Sets the value of the restrictedTradingSystems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestrictedTradingSystems(String value) {
        this.restrictedTradingSystems = value;
    }

    /**
     * Gets the value of the clientContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientContact() {
        return clientContact;
    }

    /**
     * Sets the value of the clientContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientContact(String value) {
        this.clientContact = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the internalOnlyCounterparty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalOnlyCounterparty() {
        return internalOnlyCounterparty;
    }

    /**
     * Sets the value of the internalOnlyCounterparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalOnlyCounterparty(String value) {
        this.internalOnlyCounterparty = value;
    }

    /**
     * Gets the value of the localCounterparty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalCounterparty() {
        return localCounterparty;
    }

    /**
     * Sets the value of the localCounterparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalCounterparty(String value) {
        this.localCounterparty = value;
    }

    /**
     * Gets the value of the typeOfMasterAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfMasterAgreement() {
        return typeOfMasterAgreement;
    }

    /**
     * Sets the value of the typeOfMasterAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfMasterAgreement(String value) {
        this.typeOfMasterAgreement = value;
    }

    /**
     * Gets the value of the portfolioReconcilliation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortfolioReconcilliation() {
        return portfolioReconcilliation;
    }

    /**
     * Sets the value of the portfolioReconcilliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortfolioReconcilliation(String value) {
        this.portfolioReconcilliation = value;
    }

    /**
     * Gets the value of the mexicoDocumentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMexicoDocumentation() {
        return mexicoDocumentation;
    }

    /**
     * Sets the value of the mexicoDocumentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMexicoDocumentation(String value) {
        this.mexicoDocumentation = value;
    }

    /**
     * Gets the value of the delegatedReporting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelegatedReporting() {
        return delegatedReporting;
    }

    /**
     * Sets the value of the delegatedReporting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelegatedReporting(String value) {
        this.delegatedReporting = value;
    }

    /**
     * Gets the value of the mexicoISDAProtocolAdherence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMexicoISDAProtocolAdherence() {
        return mexicoISDAProtocolAdherence;
    }

    /**
     * Sets the value of the mexicoISDAProtocolAdherence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMexicoISDAProtocolAdherence(String value) {
        this.mexicoISDAProtocolAdherence = value;
    }

    /**
     * Gets the value of the substitutedCompliance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstitutedCompliance() {
        return substitutedCompliance;
    }

    /**
     * Sets the value of the substitutedCompliance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstitutedCompliance(String value) {
        this.substitutedCompliance = value;
    }

    /**
     * Gets the value of the branchIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchIndicator() {
        return branchIndicator;
    }

    /**
     * Sets the value of the branchIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchIndicator(String value) {
        this.branchIndicator = value;
    }

}
