//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MiFID complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MiFID">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}MiFIDAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MiFID")
public class MiFID
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "MiFIDLegalEntityType", required = true)
    protected String miFIDLegalEntityType;
    @XmlAttribute(name = "TotalBalanceSheet", required = true)
    protected String totalBalanceSheet;
    @XmlAttribute(name = "TotalBalanceSheetCurrency", required = true)
    protected String totalBalanceSheetCurrency;
    @XmlAttribute(name = "OwnFunds", required = true)
    protected String ownFunds;
    @XmlAttribute(name = "OwnFundsCurrency", required = true)
    protected String ownFundsCurrency;
    @XmlAttribute(name = "ExpectedTurnover", required = true)
    protected String expectedTurnover;
    @XmlAttribute(name = "ExpectedTurnoverCurrency", required = true)
    protected String expectedTurnoverCurrency;
    @XmlAttribute(name = "LegalEntityName")
    protected String legalEntityName;
    @XmlAttribute(name = "LEI")
    protected String lei;
    @XmlAttribute(name = "LegalEntityType")
    protected String legalEntityType;
    @XmlAttribute(name = "CountryOfIncorporation")
    protected String countryOfIncorporation;
    @XmlAttribute(name = "SICCode")
    protected String sicCode;
    @XmlAttribute(name = "RegulatedBy")
    protected String regulatedBy;
    @XmlAttribute(name = "Comments")
    protected String comments;
    @XmlAttribute(name = "ClientContact")
    protected String clientContact;
    @XmlAttribute(name = "HasTheClientCarriedOutTransactions_")
    protected String hasTheClientCarriedOutTransactions;
    @XmlAttribute(name = "DoesTheSizeOfTheClientsFinancialInstrumentPortfolio_")
    protected String doesTheSizeOfTheClientsFinancialInstrumentPortfolio;
    @XmlAttribute(name = "DoesTheClientCurrentlyWork_")
    protected String doesTheClientCurrentlyWork;
    @XmlAttribute(name = "MiFIDClassificationSuggested")
    protected String miFIDClassificationSuggested;
    @XmlAttribute(name = "MiFIDClassificationOverride")
    protected String miFIDClassificationOverride;
    @XmlAttribute(name = "ProductSpecificClassification")
    protected String productSpecificClassification;
    @XmlAttribute(name = "DetailsNotes")
    protected String detailsNotes;
    @XmlAttribute(name = "MiFIDStatus")
    protected String miFIDStatus;
    @XmlAttribute(name = "MiFIDStatusOptions")
    protected String miFIDStatusOptions;

    /**
     * Gets the value of the miFIDLegalEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiFIDLegalEntityType() {
        return miFIDLegalEntityType;
    }

    /**
     * Sets the value of the miFIDLegalEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiFIDLegalEntityType(String value) {
        this.miFIDLegalEntityType = value;
    }

    /**
     * Gets the value of the totalBalanceSheet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalBalanceSheet() {
        return totalBalanceSheet;
    }

    /**
     * Sets the value of the totalBalanceSheet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalBalanceSheet(String value) {
        this.totalBalanceSheet = value;
    }

    /**
     * Gets the value of the totalBalanceSheetCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalBalanceSheetCurrency() {
        return totalBalanceSheetCurrency;
    }

    /**
     * Sets the value of the totalBalanceSheetCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalBalanceSheetCurrency(String value) {
        this.totalBalanceSheetCurrency = value;
    }

    /**
     * Gets the value of the ownFunds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnFunds() {
        return ownFunds;
    }

    /**
     * Sets the value of the ownFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnFunds(String value) {
        this.ownFunds = value;
    }

    /**
     * Gets the value of the ownFundsCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnFundsCurrency() {
        return ownFundsCurrency;
    }

    /**
     * Sets the value of the ownFundsCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnFundsCurrency(String value) {
        this.ownFundsCurrency = value;
    }

    /**
     * Gets the value of the expectedTurnover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectedTurnover() {
        return expectedTurnover;
    }

    /**
     * Sets the value of the expectedTurnover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectedTurnover(String value) {
        this.expectedTurnover = value;
    }

    /**
     * Gets the value of the expectedTurnoverCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpectedTurnoverCurrency() {
        return expectedTurnoverCurrency;
    }

    /**
     * Sets the value of the expectedTurnoverCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpectedTurnoverCurrency(String value) {
        this.expectedTurnoverCurrency = value;
    }

    /**
     * Gets the value of the legalEntityName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityName() {
        return legalEntityName;
    }

    /**
     * Sets the value of the legalEntityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityName(String value) {
        this.legalEntityName = value;
    }

    /**
     * Gets the value of the lei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEI() {
        return lei;
    }

    /**
     * Sets the value of the lei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEI(String value) {
        this.lei = value;
    }

    /**
     * Gets the value of the legalEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegalEntityType() {
        return legalEntityType;
    }

    /**
     * Sets the value of the legalEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegalEntityType(String value) {
        this.legalEntityType = value;
    }

    /**
     * Gets the value of the countryOfIncorporation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfIncorporation() {
        return countryOfIncorporation;
    }

    /**
     * Sets the value of the countryOfIncorporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfIncorporation(String value) {
        this.countryOfIncorporation = value;
    }

    /**
     * Gets the value of the sicCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSICCode() {
        return sicCode;
    }

    /**
     * Sets the value of the sicCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSICCode(String value) {
        this.sicCode = value;
    }

    /**
     * Gets the value of the regulatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatedBy() {
        return regulatedBy;
    }

    /**
     * Sets the value of the regulatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatedBy(String value) {
        this.regulatedBy = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the clientContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientContact() {
        return clientContact;
    }

    /**
     * Sets the value of the clientContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientContact(String value) {
        this.clientContact = value;
    }

    /**
     * Gets the value of the hasTheClientCarriedOutTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasTheClientCarriedOutTransactions() {
        return hasTheClientCarriedOutTransactions;
    }

    /**
     * Sets the value of the hasTheClientCarriedOutTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasTheClientCarriedOutTransactions(String value) {
        this.hasTheClientCarriedOutTransactions = value;
    }

    /**
     * Gets the value of the doesTheSizeOfTheClientsFinancialInstrumentPortfolio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoesTheSizeOfTheClientsFinancialInstrumentPortfolio() {
        return doesTheSizeOfTheClientsFinancialInstrumentPortfolio;
    }

    /**
     * Sets the value of the doesTheSizeOfTheClientsFinancialInstrumentPortfolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoesTheSizeOfTheClientsFinancialInstrumentPortfolio(String value) {
        this.doesTheSizeOfTheClientsFinancialInstrumentPortfolio = value;
    }

    /**
     * Gets the value of the doesTheClientCurrentlyWork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoesTheClientCurrentlyWork() {
        return doesTheClientCurrentlyWork;
    }

    /**
     * Sets the value of the doesTheClientCurrentlyWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoesTheClientCurrentlyWork(String value) {
        this.doesTheClientCurrentlyWork = value;
    }

    /**
     * Gets the value of the miFIDClassificationSuggested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiFIDClassificationSuggested() {
        return miFIDClassificationSuggested;
    }

    /**
     * Sets the value of the miFIDClassificationSuggested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiFIDClassificationSuggested(String value) {
        this.miFIDClassificationSuggested = value;
    }

    /**
     * Gets the value of the miFIDClassificationOverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiFIDClassificationOverride() {
        return miFIDClassificationOverride;
    }

    /**
     * Sets the value of the miFIDClassificationOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiFIDClassificationOverride(String value) {
        this.miFIDClassificationOverride = value;
    }

    /**
     * Gets the value of the productSpecificClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSpecificClassification() {
        return productSpecificClassification;
    }

    /**
     * Sets the value of the productSpecificClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSpecificClassification(String value) {
        this.productSpecificClassification = value;
    }

    /**
     * Gets the value of the detailsNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailsNotes() {
        return detailsNotes;
    }

    /**
     * Sets the value of the detailsNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailsNotes(String value) {
        this.detailsNotes = value;
    }

    /**
     * Gets the value of the miFIDStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiFIDStatus() {
        return miFIDStatus;
    }

    /**
     * Sets the value of the miFIDStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiFIDStatus(String value) {
        this.miFIDStatus = value;
    }

    /**
     * Gets the value of the miFIDStatusOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiFIDStatusOptions() {
        return miFIDStatusOptions;
    }

    /**
     * Sets the value of the miFIDStatusOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiFIDStatusOptions(String value) {
        this.miFIDStatusOptions = value;
    }

}
