//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fenergo.fdim.datagen.jaxb.dminput package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FenergoInput_QNAME = new QName("", "fenergoInput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fenergo.fdim.datagen.jaxb.dminput
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FenergoInputType }
     * 
     */
    public FenergoInputType createFenergoInputType() {
        return new FenergoInputType();
    }

    /**
     * Create an instance of {@link LegalEntity }
     * 
     */
    public LegalEntity createLegalEntity() {
        return new LegalEntity();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link MiFID }
     * 
     */
    public MiFID createMiFID() {
        return new MiFID();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Case }
     * 
     */
    public Case createCase() {
        return new Case();
    }

    /**
     * Create an instance of {@link APAC }
     * 
     */
    public APAC createAPAC() {
        return new APAC();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link DoddFrank }
     * 
     */
    public DoddFrank createDoddFrank() {
        return new DoddFrank();
    }

    /**
     * Create an instance of {@link Lookup }
     * 
     */
    public Lookup createLookup() {
        return new Lookup();
    }

    /**
     * Create an instance of {@link TradingAgreement }
     * 
     */
    public TradingAgreement createTradingAgreement() {
        return new TradingAgreement();
    }

    /**
     * Create an instance of {@link ContactAddress }
     * 
     */
    public ContactAddress createContactAddress() {
        return new ContactAddress();
    }

    /**
     * Create an instance of {@link CanadianFIU }
     * 
     */
    public CanadianFIU createCanadianFIU() {
        return new CanadianFIU();
    }

    /**
     * Create an instance of {@link SSI }
     * 
     */
    public SSI createSSI() {
        return new SSI();
    }

    /**
     * Create an instance of {@link LERole }
     * 
     */
    public LERole createLERole() {
        return new LERole();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link RoleGroup }
     * 
     */
    public RoleGroup createRoleGroup() {
        return new RoleGroup();
    }

    /**
     * Create an instance of {@link EMIR }
     * 
     */
    public EMIR createEMIR() {
        return new EMIR();
    }

    /**
     * Create an instance of {@link MexicanDrivatives }
     * 
     */
    public MexicanDrivatives createMexicanDrivatives() {
        return new MexicanDrivatives();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link FATCATAX }
     * 
     */
    public FATCATAX createFATCATAX() {
        return new FATCATAX();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FenergoInputType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fenergoInput")
    public JAXBElement<FenergoInputType> createFenergoInput(FenergoInputType value) {
        return new JAXBElement<FenergoInputType>(_FenergoInput_QNAME, FenergoInputType.class, null, value);
    }

}
