//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SSI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SSI">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}SSIAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SSI")
public class SSI
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "SecurityType", required = true)
    protected String securityType;
    @XmlAttribute(name = "Method", required = true)
    protected String method;
    @XmlAttribute(name = "PSETBIC", required = true)
    protected String psetbic;
    @XmlAttribute(name = "ACAtLocalAgent", required = true)
    protected String acAtLocalAgent;
    @XmlAttribute(name = "BGCCashAC", required = true)
    protected String bgcCashAC;
    @XmlAttribute(name = "Status")
    protected String status;
    @XmlAttribute(name = "EffectiveDate")
    protected String effectiveDate;
    @XmlAttribute(name = "SettlementCurrency")
    protected String settlementCurrency;
    @XmlAttribute(name = "AlternateCurrency")
    protected String alternateCurrency;
    @XmlAttribute(name = "ParticipantName")
    protected String participantName;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "ID1")
    protected String id1;
    @XmlAttribute(name = "ID2")
    protected String id2;
    @XmlAttribute(name = "ID3")
    protected String id3;
    @XmlAttribute(name = "ID4")
    protected String id4;
    @XmlAttribute(name = "ID5")
    protected String id5;
    @XmlAttribute(name = "ACRef")
    protected String acRef;
    @XmlAttribute(name = "Name")
    protected String name;
    @XmlAttribute(name = "LABIC")
    protected String labic;
    @XmlAttribute(name = "AddressLine1")
    protected String addressLine1;
    @XmlAttribute(name = "AddressLine2")
    protected String addressLine2;
    @XmlAttribute(name = "City")
    protected String city;
    @XmlAttribute(name = "StateProvince")
    protected String stateProvince;
    @XmlAttribute(name = "Country")
    protected String country;
    @XmlAttribute(name = "PostCode")
    protected String postCode;
    @XmlAttribute(name = "ACAtGlobalCustodian")
    protected String acAtGlobalCustodian;
    @XmlAttribute(name = "AlternateCashACNumber")
    protected String alternateCashACNumber;
    @XmlAttribute(name = "SettlementContact")
    protected String settlementContact;
    @XmlAttribute(name = "SettlementPhone")
    protected String settlementPhone;
    @XmlAttribute(name = "SpecialInstr")
    protected String specialInstr;
    @XmlAttribute(name = "ICDCashAC")
    protected String icdCashAC;
    @XmlAttribute(name = "SecurityAC")
    protected String securityAC;
    @XmlAttribute(name = "Relationship")
    protected String relationship;
    @XmlAttribute(name = "DataContact")
    protected String dataContact;
    @XmlAttribute(name = "Phone")
    protected String phone;
    @XmlAttribute(name = "Acronym")
    protected String acronym;
    @XmlAttribute(name = "AccessCode")
    protected String accessCode;
    @XmlAttribute(name = "OmniAccessCode")
    protected String omniAccessCode;
    @XmlAttribute(name = "AccountType")
    protected String accountType;
    @XmlAttribute(name = "CountryOfDomicile")
    protected String countryOfDomicile;
    @XmlAttribute(name = "CharityACRef")
    protected String charityACRef;
    @XmlAttribute(name = "LargeTraderId")
    protected String largeTraderId;
    @XmlAttribute(name = "ClientOfIA")
    protected String clientOfIA;
    @XmlAttribute(name = "ShortName")
    protected String shortName;
    @XmlAttribute(name = "OmgeoID")
    protected String omgeoID;
    @XmlAttribute(name = "BODBIC")
    protected String bodbic;
    @XmlAttribute(name = "InterestedParty1ID")
    protected String interestedParty1ID;
    @XmlAttribute(name = "InterestedParty1Name")
    protected String interestedParty1Name;
    @XmlAttribute(name = "InterestedParty1AC")
    protected String interestedParty1AC;
    @XmlAttribute(name = "InterestedParty1BIC")
    protected String interestedParty1BIC;
    @XmlAttribute(name = "InterestedParty1Contact")
    protected String interestedParty1Contact;
    @XmlAttribute(name = "InterestedParty1Phone")
    protected String interestedParty1Phone;
    @XmlAttribute(name = "InterestedParty1SpecInstr1")
    protected String interestedParty1SpecInstr1;
    @XmlAttribute(name = "InterestedParty2ID")
    protected String interestedParty2ID;
    @XmlAttribute(name = "InterestedParty2Name")
    protected String interestedParty2Name;
    @XmlAttribute(name = "InterestedParty2AC")
    protected String interestedParty2AC;
    @XmlAttribute(name = "InterestedParty2BIC")
    protected String interestedParty2BIC;
    @XmlAttribute(name = "InterestedParty2Contact")
    protected String interestedParty2Contact;
    @XmlAttribute(name = "InterestedParty2Phone")
    protected String interestedParty2Phone;
    @XmlAttribute(name = "InterestedParty2SpecInstr1")
    protected String interestedParty2SpecInstr1;
    @XmlAttribute(name = "InterestedParty3ID")
    protected String interestedParty3ID;
    @XmlAttribute(name = "InterestedParty3Name")
    protected String interestedParty3Name;
    @XmlAttribute(name = "InterestedParty3AC")
    protected String interestedParty3AC;
    @XmlAttribute(name = "InterestedParty3BIC")
    protected String interestedParty3BIC;
    @XmlAttribute(name = "InterestedParty3Contact")
    protected String interestedParty3Contact;
    @XmlAttribute(name = "InterestedParty3Phone")
    protected String interestedParty3Phone;
    @XmlAttribute(name = "InterestedParty3SpecInstr1")
    protected String interestedParty3SpecInstr1;

    /**
     * Gets the value of the securityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityType() {
        return securityType;
    }

    /**
     * Sets the value of the securityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityType(String value) {
        this.securityType = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the psetbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPSETBIC() {
        return psetbic;
    }

    /**
     * Sets the value of the psetbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPSETBIC(String value) {
        this.psetbic = value;
    }

    /**
     * Gets the value of the acAtLocalAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACAtLocalAgent() {
        return acAtLocalAgent;
    }

    /**
     * Sets the value of the acAtLocalAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACAtLocalAgent(String value) {
        this.acAtLocalAgent = value;
    }

    /**
     * Gets the value of the bgcCashAC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBGCCashAC() {
        return bgcCashAC;
    }

    /**
     * Sets the value of the bgcCashAC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBGCCashAC(String value) {
        this.bgcCashAC = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the settlementCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementCurrency() {
        return settlementCurrency;
    }

    /**
     * Sets the value of the settlementCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementCurrency(String value) {
        this.settlementCurrency = value;
    }

    /**
     * Gets the value of the alternateCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateCurrency() {
        return alternateCurrency;
    }

    /**
     * Sets the value of the alternateCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateCurrency(String value) {
        this.alternateCurrency = value;
    }

    /**
     * Gets the value of the participantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParticipantName() {
        return participantName;
    }

    /**
     * Sets the value of the participantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParticipantName(String value) {
        this.participantName = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the id1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID1() {
        return id1;
    }

    /**
     * Sets the value of the id1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID1(String value) {
        this.id1 = value;
    }

    /**
     * Gets the value of the id2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID2() {
        return id2;
    }

    /**
     * Sets the value of the id2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID2(String value) {
        this.id2 = value;
    }

    /**
     * Gets the value of the id3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID3() {
        return id3;
    }

    /**
     * Sets the value of the id3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID3(String value) {
        this.id3 = value;
    }

    /**
     * Gets the value of the id4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID4() {
        return id4;
    }

    /**
     * Sets the value of the id4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID4(String value) {
        this.id4 = value;
    }

    /**
     * Gets the value of the id5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID5() {
        return id5;
    }

    /**
     * Sets the value of the id5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID5(String value) {
        this.id5 = value;
    }

    /**
     * Gets the value of the acRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACRef() {
        return acRef;
    }

    /**
     * Sets the value of the acRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACRef(String value) {
        this.acRef = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the labic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLABIC() {
        return labic;
    }

    /**
     * Sets the value of the labic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLABIC(String value) {
        this.labic = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the stateProvince property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateProvince() {
        return stateProvince;
    }

    /**
     * Sets the value of the stateProvince property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateProvince(String value) {
        this.stateProvince = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the postCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * Sets the value of the postCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostCode(String value) {
        this.postCode = value;
    }

    /**
     * Gets the value of the acAtGlobalCustodian property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACAtGlobalCustodian() {
        return acAtGlobalCustodian;
    }

    /**
     * Sets the value of the acAtGlobalCustodian property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACAtGlobalCustodian(String value) {
        this.acAtGlobalCustodian = value;
    }

    /**
     * Gets the value of the alternateCashACNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateCashACNumber() {
        return alternateCashACNumber;
    }

    /**
     * Sets the value of the alternateCashACNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateCashACNumber(String value) {
        this.alternateCashACNumber = value;
    }

    /**
     * Gets the value of the settlementContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementContact() {
        return settlementContact;
    }

    /**
     * Sets the value of the settlementContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementContact(String value) {
        this.settlementContact = value;
    }

    /**
     * Gets the value of the settlementPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementPhone() {
        return settlementPhone;
    }

    /**
     * Sets the value of the settlementPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementPhone(String value) {
        this.settlementPhone = value;
    }

    /**
     * Gets the value of the specialInstr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialInstr() {
        return specialInstr;
    }

    /**
     * Sets the value of the specialInstr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialInstr(String value) {
        this.specialInstr = value;
    }

    /**
     * Gets the value of the icdCashAC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getICDCashAC() {
        return icdCashAC;
    }

    /**
     * Sets the value of the icdCashAC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setICDCashAC(String value) {
        this.icdCashAC = value;
    }

    /**
     * Gets the value of the securityAC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityAC() {
        return securityAC;
    }

    /**
     * Sets the value of the securityAC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityAC(String value) {
        this.securityAC = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationship(String value) {
        this.relationship = value;
    }

    /**
     * Gets the value of the dataContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataContact() {
        return dataContact;
    }

    /**
     * Sets the value of the dataContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataContact(String value) {
        this.dataContact = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the acronym property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcronym() {
        return acronym;
    }

    /**
     * Sets the value of the acronym property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcronym(String value) {
        this.acronym = value;
    }

    /**
     * Gets the value of the accessCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessCode() {
        return accessCode;
    }

    /**
     * Sets the value of the accessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessCode(String value) {
        this.accessCode = value;
    }

    /**
     * Gets the value of the omniAccessCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmniAccessCode() {
        return omniAccessCode;
    }

    /**
     * Sets the value of the omniAccessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOmniAccessCode(String value) {
        this.omniAccessCode = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the countryOfDomicile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfDomicile() {
        return countryOfDomicile;
    }

    /**
     * Sets the value of the countryOfDomicile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfDomicile(String value) {
        this.countryOfDomicile = value;
    }

    /**
     * Gets the value of the charityACRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharityACRef() {
        return charityACRef;
    }

    /**
     * Sets the value of the charityACRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharityACRef(String value) {
        this.charityACRef = value;
    }

    /**
     * Gets the value of the largeTraderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLargeTraderId() {
        return largeTraderId;
    }

    /**
     * Sets the value of the largeTraderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLargeTraderId(String value) {
        this.largeTraderId = value;
    }

    /**
     * Gets the value of the clientOfIA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientOfIA() {
        return clientOfIA;
    }

    /**
     * Sets the value of the clientOfIA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientOfIA(String value) {
        this.clientOfIA = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the omgeoID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmgeoID() {
        return omgeoID;
    }

    /**
     * Sets the value of the omgeoID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOmgeoID(String value) {
        this.omgeoID = value;
    }

    /**
     * Gets the value of the bodbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBODBIC() {
        return bodbic;
    }

    /**
     * Sets the value of the bodbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBODBIC(String value) {
        this.bodbic = value;
    }

    /**
     * Gets the value of the interestedParty1ID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty1ID() {
        return interestedParty1ID;
    }

    /**
     * Sets the value of the interestedParty1ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty1ID(String value) {
        this.interestedParty1ID = value;
    }

    /**
     * Gets the value of the interestedParty1Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty1Name() {
        return interestedParty1Name;
    }

    /**
     * Sets the value of the interestedParty1Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty1Name(String value) {
        this.interestedParty1Name = value;
    }

    /**
     * Gets the value of the interestedParty1AC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty1AC() {
        return interestedParty1AC;
    }

    /**
     * Sets the value of the interestedParty1AC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty1AC(String value) {
        this.interestedParty1AC = value;
    }

    /**
     * Gets the value of the interestedParty1BIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty1BIC() {
        return interestedParty1BIC;
    }

    /**
     * Sets the value of the interestedParty1BIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty1BIC(String value) {
        this.interestedParty1BIC = value;
    }

    /**
     * Gets the value of the interestedParty1Contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty1Contact() {
        return interestedParty1Contact;
    }

    /**
     * Sets the value of the interestedParty1Contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty1Contact(String value) {
        this.interestedParty1Contact = value;
    }

    /**
     * Gets the value of the interestedParty1Phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty1Phone() {
        return interestedParty1Phone;
    }

    /**
     * Sets the value of the interestedParty1Phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty1Phone(String value) {
        this.interestedParty1Phone = value;
    }

    /**
     * Gets the value of the interestedParty1SpecInstr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty1SpecInstr1() {
        return interestedParty1SpecInstr1;
    }

    /**
     * Sets the value of the interestedParty1SpecInstr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty1SpecInstr1(String value) {
        this.interestedParty1SpecInstr1 = value;
    }

    /**
     * Gets the value of the interestedParty2ID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty2ID() {
        return interestedParty2ID;
    }

    /**
     * Sets the value of the interestedParty2ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty2ID(String value) {
        this.interestedParty2ID = value;
    }

    /**
     * Gets the value of the interestedParty2Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty2Name() {
        return interestedParty2Name;
    }

    /**
     * Sets the value of the interestedParty2Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty2Name(String value) {
        this.interestedParty2Name = value;
    }

    /**
     * Gets the value of the interestedParty2AC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty2AC() {
        return interestedParty2AC;
    }

    /**
     * Sets the value of the interestedParty2AC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty2AC(String value) {
        this.interestedParty2AC = value;
    }

    /**
     * Gets the value of the interestedParty2BIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty2BIC() {
        return interestedParty2BIC;
    }

    /**
     * Sets the value of the interestedParty2BIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty2BIC(String value) {
        this.interestedParty2BIC = value;
    }

    /**
     * Gets the value of the interestedParty2Contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty2Contact() {
        return interestedParty2Contact;
    }

    /**
     * Sets the value of the interestedParty2Contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty2Contact(String value) {
        this.interestedParty2Contact = value;
    }

    /**
     * Gets the value of the interestedParty2Phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty2Phone() {
        return interestedParty2Phone;
    }

    /**
     * Sets the value of the interestedParty2Phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty2Phone(String value) {
        this.interestedParty2Phone = value;
    }

    /**
     * Gets the value of the interestedParty2SpecInstr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty2SpecInstr1() {
        return interestedParty2SpecInstr1;
    }

    /**
     * Sets the value of the interestedParty2SpecInstr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty2SpecInstr1(String value) {
        this.interestedParty2SpecInstr1 = value;
    }

    /**
     * Gets the value of the interestedParty3ID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty3ID() {
        return interestedParty3ID;
    }

    /**
     * Sets the value of the interestedParty3ID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty3ID(String value) {
        this.interestedParty3ID = value;
    }

    /**
     * Gets the value of the interestedParty3Name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty3Name() {
        return interestedParty3Name;
    }

    /**
     * Sets the value of the interestedParty3Name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty3Name(String value) {
        this.interestedParty3Name = value;
    }

    /**
     * Gets the value of the interestedParty3AC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty3AC() {
        return interestedParty3AC;
    }

    /**
     * Sets the value of the interestedParty3AC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty3AC(String value) {
        this.interestedParty3AC = value;
    }

    /**
     * Gets the value of the interestedParty3BIC property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty3BIC() {
        return interestedParty3BIC;
    }

    /**
     * Sets the value of the interestedParty3BIC property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty3BIC(String value) {
        this.interestedParty3BIC = value;
    }

    /**
     * Gets the value of the interestedParty3Contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty3Contact() {
        return interestedParty3Contact;
    }

    /**
     * Sets the value of the interestedParty3Contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty3Contact(String value) {
        this.interestedParty3Contact = value;
    }

    /**
     * Gets the value of the interestedParty3Phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty3Phone() {
        return interestedParty3Phone;
    }

    /**
     * Sets the value of the interestedParty3Phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty3Phone(String value) {
        this.interestedParty3Phone = value;
    }

    /**
     * Gets the value of the interestedParty3SpecInstr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestedParty3SpecInstr1() {
        return interestedParty3SpecInstr1;
    }

    /**
     * Sets the value of the interestedParty3SpecInstr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestedParty3SpecInstr1(String value) {
        this.interestedParty3SpecInstr1 = value;
    }

}
