//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.24 at 05:30:03 PM BST 
//


package com.fenergo.fdim.datagen.jaxb.dminput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TradingAgreement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradingAgreement">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbstractInputEntityType">
 *       &lt;attGroup ref="{}TradingAgreementAttrGroup"/>
 *       &lt;anyAttribute processContents='skip'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradingAgreement")
public class TradingAgreement
    extends AbstractInputEntityType
{

    @XmlAttribute(name = "TAID")
    protected String taid;
    @XmlAttribute(name = "TAStatus")
    protected String taStatus;
    @XmlAttribute(name = "TACategory")
    protected String taCategory;
    @XmlAttribute(name = "TAType")
    protected String taType;
    @XmlAttribute(name = "TAVersion")
    protected String taVersion;
    @XmlAttribute(name = "DateOfSigning")
    protected String dateOfSigning;
    @XmlAttribute(name = "CatalogNumber")
    protected String catalogNumber;
    @XmlAttribute(name = "AgreementSupplement")
    protected String agreementSupplement;
    @XmlAttribute(name = "ContractingEntity")
    protected String contractingEntity;
    @XmlAttribute(name = "Comments")
    protected String comments;

    /**
     * Gets the value of the taid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAID() {
        return taid;
    }

    /**
     * Sets the value of the taid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAID(String value) {
        this.taid = value;
    }

    /**
     * Gets the value of the taStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAStatus() {
        return taStatus;
    }

    /**
     * Sets the value of the taStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAStatus(String value) {
        this.taStatus = value;
    }

    /**
     * Gets the value of the taCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTACategory() {
        return taCategory;
    }

    /**
     * Sets the value of the taCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTACategory(String value) {
        this.taCategory = value;
    }

    /**
     * Gets the value of the taType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAType() {
        return taType;
    }

    /**
     * Sets the value of the taType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAType(String value) {
        this.taType = value;
    }

    /**
     * Gets the value of the taVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTAVersion() {
        return taVersion;
    }

    /**
     * Sets the value of the taVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAVersion(String value) {
        this.taVersion = value;
    }

    /**
     * Gets the value of the dateOfSigning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfSigning() {
        return dateOfSigning;
    }

    /**
     * Sets the value of the dateOfSigning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfSigning(String value) {
        this.dateOfSigning = value;
    }

    /**
     * Gets the value of the catalogNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogNumber() {
        return catalogNumber;
    }

    /**
     * Sets the value of the catalogNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogNumber(String value) {
        this.catalogNumber = value;
    }

    /**
     * Gets the value of the agreementSupplement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementSupplement() {
        return agreementSupplement;
    }

    /**
     * Sets the value of the agreementSupplement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementSupplement(String value) {
        this.agreementSupplement = value;
    }

    /**
     * Gets the value of the contractingEntity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractingEntity() {
        return contractingEntity;
    }

    /**
     * Sets the value of the contractingEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractingEntity(String value) {
        this.contractingEntity = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
