//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.30 at 10:19:05 PM GMT 
//


package com.fenergo.fdim.datagen.jaxb.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigurationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="output_file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="batch_size" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="root_entities" type="{http://com.fenergo.fdim/Configuration}ListOfRootEntityType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationType", propOrder = {
    "outputFile",
    "batchSize",
    "rootEntities"
})
public class ConfigurationType {

    @XmlElement(name = "output_file", required = true)
    protected String outputFile;
    @XmlElement(name = "batch_size", required = true)
    protected long batchSize;
    @XmlElement(name = "root_entities", required = true)
    protected ListOfRootEntityType rootEntities;

    /**
     * Gets the value of the outputFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFile() {
        return outputFile;
    }

    /**
     * Sets the value of the outputFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFile(String value) {
        this.outputFile = value;
    }

    /**
     * Gets the value of the batchSize property.
     * 
     */
    public long getBatchSize() {
        return batchSize;
    }

    /**
     * Sets the value of the batchSize property.
     * 
     */
    public void setBatchSize(long value) {
        this.batchSize = value;
    }

    /**
     * Gets the value of the rootEntities property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfRootEntityType }
     *     
     */
    public ListOfRootEntityType getRootEntities() {
        return rootEntities;
    }

    /**
     * Sets the value of the rootEntities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfRootEntityType }
     *     
     */
    public void setRootEntities(ListOfRootEntityType value) {
        this.rootEntities = value;
    }

}
