//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.30 at 10:19:05 PM GMT 
//


package com.fenergo.fdim.datagen.jaxb.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RootEntityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RootEntityType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://com.fenergo.fdim/Configuration}AbstractEntityType">
 *       &lt;sequence>
 *         &lt;element name="child_entities" type="{http://com.fenergo.fdim/Configuration}ListOfChildEntityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RootEntityType", propOrder = {
    "childEntities"
})
public class RootEntityType
    extends AbstractEntityType
{

    @XmlElement(name = "child_entities")
    protected ListOfChildEntityType childEntities;

    /**
     * Gets the value of the childEntities property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfChildEntityType }
     *     
     */
    public ListOfChildEntityType getChildEntities() {
        return childEntities;
    }

    /**
     * Sets the value of the childEntities property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfChildEntityType }
     *     
     */
    public void setChildEntities(ListOfChildEntityType value) {
        this.childEntities = value;
    }

}
